TechnologyEnhancedLearning/LearningHub.Nhs.WebUI

- .github/pull_request_template.md
- README.md
[TD-970](https://hee-tis.atlassian.net/browse/TD-970)
Updates the repository readme file with some basic content. Since this project has a dependency on the User API project, this content can be reviewed again when the readme for that is created in TD-972. For now, please check for obvious errors to omissions.
-----
I have:
[TD-970]: https://hee-tis.atlassian.net/browse/TD-970?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> TD-970 Update the Web.UI repository readme

- README.md
> Update CI check trigger

- .github/azure-pipeline-database-ci.yml
- .github/azure-pipeline-openapi-reportapi-ci.yml
- .github/azure-pipeline-webui-ci.yml
- README.md
> bring RC changes to Rc hot fix

- LearningHub.Nhs.WebUI/Scripts/vuesrc/resource/ResourceContent.vue
- LearningHub.Nhs.WebUI/Scripts/vuesrc/resource/blocks/ImageCarouselViewer.vue
> Fixed the vue build error in windows-latest in github

- LearningHub.Nhs.WebUI/package-lock.json
- LearningHub.Nhs.WebUI/package.json
Reverts TechnologyEnhancedLearning/LearningHub.Nhs.WebUI#103
> Revert "Bump axios from 0.19.1 to 1.6.0 in /LearningHub.Nhs.WebUI"

- LearningHub.Nhs.WebUI/Styles/nhsuk/layout.scss
> Fix accessibility issues in My Bookmarks section

- LearningHub.Nhs.WebUI/Views/Search/_ResourceSearchResult.cshtml
- LearningHub.Nhs.WebUI/Views/Search/_SubmitFeedback.cshtml
- LearningHub.Nhs.WebUI/Views/Shared/_NavPartial.cshtml
> Fix learner search page and search results accessibility issues

- LearningHub.Nhs.WebUI/Scripts/vuesrc/contribute/ContentGenericFile.vue
- LearningHub.Nhs.WebUI/Scripts/vuesrc/models/contribute/contributeResourceModel.ts
- LearningHub.Nhs.WebUI/Views/Resource/_ResourceItem.cshtml
https://hee-tis.atlassian.net/browse/TD-3541
Removed the outdated feature from the Generic file Contribution process
-----
I have:
> TD-3541- Zip file can be marked as SCORM outdated feature

- LearningHub.Nhs.WebUI/Scripts/vuesrc/globalcomponents/IconButton.vue
- LearningHub.Nhs.WebUI/Scripts/vuesrc/resource/blocks/QuestionBlock.vue
- LearningHub.Nhs.WebUI/Scripts/vuesrc/resource/blocks/SingleQuestionAnswerView.vue
- LearningHub.Nhs.WebUI/Views/Resource/_RatingSummary.cshtml
> Fix learning resources accessibility issues

- WebAPI/LearningHub.Nhs.Database/Stored Procedures/Activity/ScormActivityGetSummary.sql
[TD-3337](https://hee-tis.atlassian.net/browse/TD-3337)
Bookmarking and suspend data not being recalled  fix
-----
I have:
> TD-3337 Updated Scorm Activity Summary where clause

- WebAPI/LearningHub.Nhs.Database/Stored Procedures/Resources/GetDashboardResources.sql
> Merge phoenix  changes to CI

- LearningHub.Nhs.WebUI/Configuration/Settings.cs
- LearningHub.Nhs.WebUI/Controllers/Api/ContributeController.cs
- LearningHub.Nhs.WebUI/Controllers/ResourceController.cs
- LearningHub.Nhs.WebUI/Interfaces/IFileService.cs
- LearningHub.Nhs.WebUI/Services/FileService.cs
- LearningHub.Nhs.WebUI/appsettings.json
- WebAPI/LearningHub.Nhs.API/Controllers/ResourceController.cs
- WebAPI/LearningHub.Nhs.Services.Interface/IResourceService.cs
- WebAPI/LearningHub.Nhs.Services/ResourceService.cs
[TD 3023](https://hee-tis.atlassian.net/browse/TD-3023)
Added the logic to move associated files of deleted resources to archive storage
-----
I have:
> TD 3023 Manage Azure file storage

- WebAPI/LearningHub.Nhs.Database/Stored Procedures/Activity/GetUserLearningActivities.sql
- WebAPI/LearningHub.Nhs.Database/Stored Procedures/Activity/GetUserLearningActivitiesCount.sql
- WebAPI/LearningHub.Nhs.Repository/Activity/ResourceActivityRepository.cs
- WebAPI/LearningHub.Nhs.Services/MyLearningService.cs
https://hee-tis.atlassian.net/browse/TD-3886
Fixed below issues:
1. Filter Complete is returning in progress status as well. 
2. The downloaded filter is not working.
**_After code fix:_**
-----
I have:
> TD-3886: Fix Issues Related to WEB UI-My Learning page

- LearningHub.Nhs.WebUI/Scripts/vuesrc/roadmap/roadmap.vue
- LearningHub.Nhs.WebUI/Styles/nhsuk/common.scss
- LearningHub.Nhs.WebUI/Views/Policies/AcceptableUsePolicy.cshtml
- LearningHub.Nhs.WebUI/Views/Policies/ContentPolicy.cshtml
> Fix footer links accessibility issues

- WebAPI/LearningHub.Nhs.Services/MyLearningService.cs
> Missed this file part of the Azure to GitHub migration

- LearningHub.Nhs.WebUI/Views/Resource/_ResourceItem.cshtml
> MergeChanges-RC

- LearningHub.Nhs.WebUI/Views/Resource/_ResourceItem.cshtml
> View HTML   Resource Changes

- LearningHub.Nhs.WebUI/Views/Resource/_ResourceItem.cshtml
> HTML filter added

- WebAPI/LearningHub.Nhs.Services/MyLearningService.cs
[TD-3726](https://hee-tis.atlassian.net/browse/TD-3726)
optimized the cert query for media resources
-----
I have:
[TD-3726]: https://hee-tis.atlassian.net/browse/TD-3726?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> TD-3726 Updated cert check for media resources

- LearningHub.Nhs.WebUI/Controllers/AccountController.cs
> Defect Fixes-TD-3744-Job role with slash in causes error during registration

- WebAPI/LearningHub.Nhs.Database/Stored Procedures/Resources/GetDashboardResources.sql
https://hee-tis.atlassian.net/browse/TD-3688
Issue fix for Completed status resource showing in In progress tray
**_Before code fix:_**
**_After code fix:_**
-----
I have:
> TD-3688: Issue fix for Completed status resource showing in In progress tray

- LearningHub.Nhs.WebUI/Helpers/ViewActivityHelper.cs
[TD-3993](https://hee-tis.atlassian.net/browse/TD-3993)
video duration bugfix.
-----
I have:
[TD-3993]: https://hee-tis.atlassian.net/browse/TD-3993?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> TD-3993 video duration text bugfix

- LearningHub.Nhs.WebUI/Views/Home/Aboutus.cshtml
- LearningHub.Nhs.WebUI/Views/Home/Contactus.cshtml
TD-3959
Update LH footer pages review dates 
-----
I have:
> TD-3959-Update-Review Date-in Contact US/About us

- LearningHub.Nhs.WebUI/Controllers/AccountController.cs
https://hee-tis.atlassian.net/browse/TD-3953
Changed the method name for fetching role name in account creation
Before code change: 
After code change:
-----
I have:
> TD-3953 manager role fix

- LearningHub.Nhs.WebUI/Helpers/ViewActivityHelper.cs
- LearningHub.Nhs.WebUI/Views/Bookmark/_BookmarkAction.cshtml
- LearningHub.Nhs.WebUI/Views/MyLearning/LearningCertificate.cshtml
- LearningHub.Nhs.WebUI/Views/Shared/_NavPartial.cshtml
> Merge RC changes to LH Phoenix 

- AdminUI/LearningHub.Nhs.AdminUI/LearningHub.Nhs.AdminUI.csproj
- LearningHub.Nhs.WebUI/LearningHub.Nhs.WebUI.csproj
- WebAPI/LearningHub.Nhs.API/LearningHub.Nhs.Api.csproj
- WebAPI/LearningHub.Nhs.Api.Shared/LearningHub.Nhs.Api.Shared.csproj
- WebAPI/LearningHub.Nhs.Api.UnitTests/LearningHub.Nhs.Api.UnitTests.csproj
- WebAPI/LearningHub.Nhs.Repository.Interface/LearningHub.Nhs.Repository.Interface.csproj
- WebAPI/LearningHub.Nhs.Repository/LearningHub.Nhs.Repository.csproj
- WebAPI/LearningHub.Nhs.Services.Interface/LearningHub.Nhs.Services.Interface.csproj
- WebAPI/LearningHub.Nhs.Services.UnitTests/LearningHub.Nhs.Services.UnitTests.csproj
- WebAPI/LearningHub.Nhs.Services/LearningHub.Nhs.Services.csproj
- WebAPI/MigrationTool/LearningHub.Nhs.Migration.ConsoleApp/LearningHub.Nhs.Migration.ConsoleApp.csproj
- WebAPI/MigrationTool/LearningHub.Nhs.Migration.Interface/LearningHub.Nhs.Migration.Interface.csproj
- WebAPI/MigrationTool/LearningHub.Nhs.Migration.Models/LearningHub.Nhs.Migration.Models.csproj
- WebAPI/MigrationTool/LearningHub.Nhs.Migration.Staging.Repository/LearningHub.Nhs.Migration.Staging.Repository.csproj
- WebAPI/MigrationTool/LearningHub.Nhs.Migration.UnitTests/LearningHub.Nhs.Migration.UnitTests.csproj
- WebAPI/MigrationTool/LearningHub.Nhs.Migration/LearningHub.Nhs.Migration.csproj
> LH-Model    Version Update

- LearningHub.Nhs.WebUI/Models/MyLearningViewModel.cs
- LearningHub.Nhs.WebUI/Views/MyLearning/_filterSummary.cshtml
- WebAPI/LearningHub.Nhs.Database/Stored Procedures/Activity/GetUserLearningActivities.sql
- WebAPI/LearningHub.Nhs.Database/Stored Procedures/Activity/GetUserLearningActivitiesCount.sql
1. Filter issue with combination of Completed and eLearning fixed. Filter tag text and checkbox label changed For Completed and In Progress
**_Filter text change_**
-----
I have:
> TD-2954: 1. Filter issue with combination of Completed and eLearning fixed. Filter tag text and checkbox label changed For Completed and In Progress

- LearningHub.Nhs.WebUI/Views/Shared/_GoogleTagManagerNoScriptPartial.cshtml
- LearningHub.Nhs.WebUI/Views/Shared/_GoogleTagManagerPartial.cshtml
https://hee-tis.atlassian.net/browse/TD-4009
Added the condition to use  Google Tag Manager to track only Prod Details. 
-----
I have:
> TD-4009: Google Tag Manager tracking for all Non Prod Environments

- AdminUI/LearningHub.Nhs.AdminUI/LearningHub.Nhs.AdminUI.csproj
- AdminUI/LearningHub.Nhs.AdminUI/Views/Catalogue/Edit.cshtml
- LearningHub.Nhs.WebUI/LearningHub.Nhs.WebUI.csproj
- WebAPI/LearningHub.Nhs.API/LearningHub.Nhs.Api.csproj
- WebAPI/LearningHub.Nhs.Database/Scripts/Pre-Deploy/Script.PreDeployment.sql
- WebAPI/LearningHub.Nhs.Database/Stored Procedures/Hierarchy/CatalogueCreate.sql
https://hee-tis.atlassian.net/browse/TD-4016
Removed character limit from catalogue description
-----
I have:
> TD-4016:Remove character limit from catalogue description

- WebAPI/LearningHub.Nhs.Api.Shared/LearningHub.Nhs.Api.Shared.csproj
- WebAPI/LearningHub.Nhs.Api.UnitTests/LearningHub.Nhs.Api.UnitTests.csproj
- WebAPI/LearningHub.Nhs.Database/Stored Procedures/Activity/GetUserLearningActivities.sql
- WebAPI/LearningHub.Nhs.Database/Stored Procedures/Activity/GetUserLearningActivitiesCount.sql
- WebAPI/LearningHub.Nhs.Repository.Interface/LearningHub.Nhs.Repository.Interface.csproj
- WebAPI/LearningHub.Nhs.Repository/LearningHub.Nhs.Repository.csproj
- WebAPI/LearningHub.Nhs.Services.Interface/LearningHub.Nhs.Services.Interface.csproj
- WebAPI/LearningHub.Nhs.Services.UnitTests/LearningHub.Nhs.Services.UnitTests.csproj
- WebAPI/LearningHub.Nhs.Services/LearningHub.Nhs.Services.csproj
- WebAPI/MigrationTool/LearningHub.Nhs.Migration.ConsoleApp/LearningHub.Nhs.Migration.ConsoleApp.csproj
- WebAPI/MigrationTool/LearningHub.Nhs.Migration.Interface/LearningHub.Nhs.Migration.Interface.csproj
- WebAPI/MigrationTool/LearningHub.Nhs.Migration.Models/LearningHub.Nhs.Migration.Models.csproj
- WebAPI/MigrationTool/LearningHub.Nhs.Migration.Staging.Repository/LearningHub.Nhs.Migration.Staging.Repository.csproj
- WebAPI/MigrationTool/LearningHub.Nhs.Migration.UnitTests/LearningHub.Nhs.Migration.UnitTests.csproj
- WebAPI/MigrationTool/LearningHub.Nhs.Migration/LearningHub.Nhs.Migration.csproj
Filter issues for assessment resolved
**_Assessment-Passed_**
**_Assessent-Failed_**
**_Assessment-Passed&Failed_**
-----
I have:
> TD-2954: Filter issues for assessment resolved

- WebAPI/LearningHub.Nhs.Database/LearningHub.Nhs.Database.sqlproj
> Modified the build action to None

- WebAPI/LearningHub.Nhs.Database/Scripts/Pre-Deploy/Script.PreDeployment.sql
https://hee-tis.atlassian.net/browse/TD-4016
Deployment issue fix
-----
I have:
> TD-4016: Deployment issue fix

- WebAPI/LearningHub.Nhs.Database/LearningHub.Nhs.Database.sqlproj
- WebAPI/LearningHub.Nhs.Database/Scripts/Post-Deploy/Script.PostDeployment.sql
- WebAPI/LearningHub.Nhs.Database/Scripts/Post-Deploy/Scripts/TD-4016_Alter_CatalogueNodeVersionTable.sql
- WebAPI/LearningHub.Nhs.Database/Scripts/Pre-Deploy/Script.PreDeployment.sql
https://hee-tis.atlassian.net/browse/TD-4016
Deployment fail fix
-----
I have:
> TD-4016:Build fail fix

- WebAPI/LearningHub.Nhs.Database/Stored Procedures/Activity/GetUserLearningActivities.sql
- WebAPI/LearningHub.Nhs.Repository/Activity/ResourceActivityRepository.cs
Filter “In Progress“ and “Assessment“ issue fix
-----
I have:
> TD-2954: Filter fix

- WebAPI/LearningHub.Nhs.Database/LearningHub.Nhs.Database.sqlproj
- WebAPI/LearningHub.Nhs.Database/Scripts/Post-Deploy/Script.PostDeployment.sql
- WebAPI/LearningHub.Nhs.Database/Scripts/Post-Deploy/Scripts/TD-4016_Alter_CatalogueNodeVersionTable.sql
- WebAPI/LearningHub.Nhs.Database/Stored Procedures/Activity/GetUserLearningActivitiesCount.sql
- WebAPI/LearningHub.Nhs.Database/Tables/Hierarchy/CatalogueNodeVersion.sql
Missing logic added
-----
I have:
> TD-2954: Missing logic added

- LearningHub.Nhs.WebUI/Controllers/Api/ContributeController.cs
- LearningHub.Nhs.WebUI/Controllers/ResourceController.cs
- LearningHub.Nhs.WebUI/Interfaces/IFileService.cs
- LearningHub.Nhs.WebUI/Interfaces/IResourceService.cs
- LearningHub.Nhs.WebUI/Services/FileService.cs
- LearningHub.Nhs.WebUI/Services/ResourceService.cs
- WebAPI/LearningHub.Nhs.API/Controllers/ResourceController.cs
- WebAPI/LearningHub.Nhs.Services.Interface/IResourceService.cs
- WebAPI/LearningHub.Nhs.Services/ResourceService.cs
management of files associated with deleted draft and unpublished resource respectively
-----
I have:
> TD-3023 fix for unpublished and deleted draft

- LearningHub.Nhs.WebUI/Views/Catalogue/Index.cshtml
- LearningHub.Nhs.WebUI/Views/Catalogue/_SearchBar.cshtml
- LearningHub.Nhs.WebUI/Views/Home/_CatalogueCard.cshtml
- LearningHub.Nhs.WebUI/Views/Home/_ResourceCard.cshtml
- LearningHub.Nhs.WebUI/Views/Resource/_ResourceInformation.cshtml
- LearningHub.Nhs.WebUI/Views/Search/_SearchBar.cshtml
- LearningHub.Nhs.WebUI/Views/Shared/_NavPartial.cshtml
> Merge-Apply additional corrections for TD3162 and TD3163

- LearningHub.Nhs.WebUI/Models/MyLearningViewModel.cs
- LearningHub.Nhs.WebUI/Views/MyLearning/_filterSummary.cshtml
_TD-###_
Corrected the naming convention for uniformity [In Progress to In progress]
-----
I have:
> Corrected the naming convention for uniformity

- LearningHub.Nhs.WebUI/Controllers/Api/ScormController.cs
- WebAPI/LearningHub.Nhs.Database/Stored Procedures/Activity/ScormActivityComplete.sql
https://hee-tis.atlassian.net/browse/TD-1325
reverted the changes as it is throwing LMS server related issues.
-----
I have:
> TD-1325: Reverted the changes as it is causing some LMS server issues

- LearningHub.Nhs.WebUI/Controllers/MyLearningController.cs
- LearningHub.Nhs.WebUI/Models/Learning/CertificateDetails.cs
- LearningHub.Nhs.WebUI/Views/MyLearning/LearningCertificate.cshtml
https://hee-tis.atlassian.net/browse/TD-2959?atlOrigin=eyJpIjoiZTE3ZjU2ZmMxNjQ4NDc2Y2E1NTE1MjNhMGY4NzcxNzMiLCJwIjoiaiJ9
Added links to the existing html for the pdf certificate generation
Before
After:
-----
I have:
> TD-2959:Added hyperlinks to the existing html for certificate pdf generation

- LearningHub.Nhs.WebUI/Services/ContributeService.cs
_[TD-3311](https://hee-tis.atlassian.net/browse/TD-3311?atlOrigin=eyJpIjoiZGFkMDBkNTkzY2E4NGM4YTg3MjY5YzdmMDM5NTk1Y2UiLCJwIjoiaiJ9)_
_Removed special characters from file names during chunk file upload. This is already done in normal file upload._
Before: 
After:
-----
I have:
[TD-3311]: https://hee-tis.atlassian.net/browse/TD-3311?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> TD-3311: Removed special characters in filename during file upload

- WebAPI/LearningHub.Nhs.Services/CatalogueService.cs
https://hee-tis.atlassian.net/browse/TD-4057
Catalogue description characters limited to 3000  to send to  findwise
-----
I have:
> TD-4057: Catalogue description characters limited to 3000  to send to  findwise

- WebAPI/LearningHub.Nhs.Services/CatalogueService.cs
https://hee-tis.atlassian.net/browse/TD-4058
Fixed the issues related to the assessment publishing.
-----
I have:
> TD-4058: Assessment - Submit answers results in unknown error

- LearningHub.Nhs.WebUI/Services/FileService.cs
TD-3023
Issues with output directory and input directory share client being active at the same time
revalidate a move to input directory request.
Nil
-----
I have:
> TD-3023 Azureshareclient bugfix and logic to revalidate input directory

- WebAPI/LearningHub.Nhs.Database/Stored Procedures/Activity/GetUserLatestActivityCheck.sql
- WebAPI/LearningHub.Nhs.Database/Stored Procedures/Activity/GetUserLearningActivities.sql
- WebAPI/LearningHub.Nhs.Database/Stored Procedures/Activity/GetUserLearningActivitiesCount.sql
- WebAPI/LearningHub.Nhs.Repository/Activity/ResourceActivityRepository.cs
Issues with audio,video,assessment resolved. Also handled duplicate records issue.
-----
I have:
> TD-2954: Issues with audio,video,assessment resolved. Also handled duplicate records issue.

- WebAPI/LearningHub.Nhs.Database/Stored Procedures/Hierarchy/CatalogueUpdate.sql
- WebAPI/LearningHub.Nhs.Services/CatalogueService.cs
https://hee-tis.atlassian.net/browse/TD-4057
Findwise limit varies when update,show catalogue setting issue resolved
-----
I have:
> TD-4057: Findwise limit varies when update,show catalogue setting issue resolved

- WebAPI/LearningHub.Nhs.Database/Stored Procedures/Activity/GetUserLatestActivityCheck.sql
- WebAPI/LearningHub.Nhs.Database/Stored Procedures/Activity/GetUserLearningActivities.sql
- WebAPI/LearningHub.Nhs.Repository/Activity/ResourceActivityRepository.cs
https://hee-tis.atlassian.net/browse/TD-4067
Issue in elearning and assessment when multiple version is available has been resolved
**_assessmet_**
-----
I have:
> TD-4067: Issue in elearning when multiple version is available has been resolved

- WebAPI/LearningHub.Nhs.Services/MyLearningService.cs
https://hee-tis.atlassian.net/browse/TD-4108
Certificate issue for assessment and audio/video has been resolved
-----
I have:
> TD-4108: Certificate issue for assessment and audio/video has been resolved

- WebAPI/LearningHub.Nhs.Database/Stored Procedures/Activity/GetUserLatestActivityCheck.sql
- WebAPI/LearningHub.Nhs.Database/Stored Procedures/Activity/GetUserLearningActivities.sql
- WebAPI/LearningHub.Nhs.Database/Stored Procedures/Activity/GetUserLearningActivitiesCount.sql
https://hee-tis.atlassian.net/browse/TD-4106
DUplicate record for assessment with dafault date issue resolved
-----
I have:
> TD-4106: DUplicate record for assessment with dafault date issue resolved

- WebAPI/LearningHub.Nhs.Database/Stored Procedures/Activity/GetUserLatestActivityCheck.sql
- WebAPI/LearningHub.Nhs.Database/Stored Procedures/Activity/GetUserLearningActivities.sql
- WebAPI/LearningHub.Nhs.Database/Stored Procedures/Activity/GetUserLearningActivitiesCount.sql
- WebAPI/LearningHub.Nhs.Services/MyLearningService.cs
https://hee-tis.atlassian.net/browse/TD-4108
Certficate issue for assessments resolved. Failed record not showing issue resolved.
-----
I have:
> TD-4108:Certficate issue for assessments resolved. Failed record not showing issue resolved.

- WebAPI/LearningHub.Nhs.Database/Stored Procedures/Activity/GetUserLearningActivities.sql
- WebAPI/LearningHub.Nhs.Database/Stored Procedures/Activity/GetUserLearningActivitiesCount.sql
https://hee-tis.atlassian.net/browse/TD-4106
fixed the Issue with informal assessment duplicate record while searching
-----
I have:
> TD-4016: Issue with informal assessment duplicate record while searching

- WebAPI/LearningHub.Nhs.Services/MyLearningService.cs
- WebAPI/LearningHub.Nhs.Services/UserLearningRecordService.cs
https://hee-tis.atlassian.net/browse/TD-3736
Performance improvement implemented in Admin UI. Used stored procedures to bind the data from DB.
-----
I have:
> TD-3736: Performance improvement implemented in Admin UI. Used stored procedures to bind the data from DB.

- WebAPI/LearningHub.Nhs.Services/MyLearningService.cs
https://hee-tis.atlassian.net/browse/TD-4121
Fixed the issue related to the assessment visibility
-----
I have:
> TD-4121: Fixed the issue with the assessment certificate view

- LearningHub.Nhs.WebUI/Scripts/vuesrc/resource/CaseOrAssessmentResource.vue
- LearningHub.Nhs.WebUI/Scripts/vuesrc/resource/blocks/BlocksView.vue
_[TD-3707](https://hee-tis.atlassian.net/browse/TD-3707?atlOrigin=eyJpIjoiNzBhNmVhYzhlZThlNDA3MjkxMjNiN2E4NGE0ZmJiMWMiLCJwIjoiaiJ9)_
Fixed question focusing issue in assessments.
-----
I have:
[TD-3707]: https://hee-tis.atlassian.net/browse/TD-3707?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> TD-3707: fixed question focus issue in assessments

- WebAPI/LearningHub.Nhs.Database/Stored Procedures/Resources/GetDashboardResources.sql
https://hee-tis.atlassian.net/browse/TD-4115
My accessed learning’ tray, showing this completed (passed) informal assessment not showing on the ‘Certificates’ section - fixed
-----
I have:
> TD-4115- My accessed learning tray issues

- LearningHub.Nhs.WebUI/Controllers/Api/ContributeController.cs
> TD-3023 Issue with video and wsi in question block

- LearningHub.Nhs.WebUI/Services/FileService.cs
Delete empty folder
-----
I have:
> TD-3023 Delete empty folder

- LearningHub.Nhs.WebUI/Controllers/OpenAthensController.cs
https://hee-tis.atlassian.net/browse/TD-4111
Null exception will be inserted into DB for ClientID and Origin
-----
I have:
> TD-4111: Null exception will be inserted into DB for ClientID and Origin

- WebAPI/LearningHub.Nhs.Database/Tables/Resource/ExternalReference.sql
- WebAPI/LearningHub.Nhs.Database/Tables/Resource/ScormResourceVersion.sql
- WebAPI/LearningHub.Nhs.Database/Tables/Resource/ScormResourceVersionManifest.sql
https://hee-tis.atlassian.net/browse/TD-4209
Add Script file created for Index
-----
I have:
> TD-4209:Add Script file created for Index

- WebAPI/LearningHub.Nhs.Database/Stored Procedures/Resources/AssessmentContentBlockCollectionGetAll.sql
- WebAPI/LearningHub.Nhs.Database/Stored Procedures/Resources/AssessmentGuidanceBlockCollectionGetAll.sql
- WebAPI/LearningHub.Nhs.Database/Stored Procedures/Resources/CaseBlockCollectionGetAll.sql
> TD-3023 sp syntax error update

- WebAPI/LearningHub.Nhs.Database/LearningHub.Nhs.Database.sqlproj
> sql sp update

- LearningHub.Nhs.WebUI/Controllers/Api/ContributeController.cs
- WebAPI/LearningHub.Nhs.Services/ResourceService.cs
TD-3023
Video files within question block bugfix
-----
I have:
> Fix for video  and video files within a case and assessment resource

- WebAPI/LearningHub.Nhs.API/Controllers/ResourceController.cs
- WebAPI/LearningHub.Nhs.Repository.Interface/Resources/IResourceVersionRepository.cs
- WebAPI/LearningHub.Nhs.Repository/Resources/ResourceVersionRepository.cs
- WebAPI/LearningHub.Nhs.Services.Interface/IResourceService.cs
- WebAPI/LearningHub.Nhs.Services/ResourceService.cs
> Merge Releases/lh telescopium  changes to Test Env

- AdminUI/LearningHub.Nhs.AdminUI/Scripts/vuesrc/content/cmsPageRow.vue
- LearningHub.Nhs.WebUI/Scripts/vuesrc/resource/ResourceContent.vue
- LearningHub.Nhs.WebUI/Views/Home/_CmsVideo.cshtml
- WebAPI/LearningHub.Nhs.Database/Scripts/Post-Deploy/Scripts/TD-4031_AMStoMKIOMigration.sql
> Making consistent layout on mediakind player and update sql script file

- AdminUI/LearningHub.Nhs.AdminUI/Configuration/WebSettings.cs
- AdminUI/LearningHub.Nhs.AdminUI/Controllers/ResourceController.cs
- AdminUI/LearningHub.Nhs.AdminUI/Interfaces/IFileService.cs
- AdminUI/LearningHub.Nhs.AdminUI/Services/FileService.cs
- AdminUI/LearningHub.Nhs.AdminUI/appsettings.json
[TD-4054](https://hee-tis.atlassian.net/browse/TD-4054)
archive html and scorm content on admin ui
-----
I have:
[TD-4054]: https://hee-tis.atlassian.net/browse/TD-4054?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> TD-4054 archive extracted content folders for html and scorm resource.

- LearningHub.Nhs.WebUI/Views/Home/_CmsVideo.cshtml
https://hee-tis.atlassian.net/browse/TD-4274)
-----
I have:
> Apple device fix recommended by MK

- LearningHub.Nhs.WebUI/Views/Resource/_ResourceItem.cshtml
https://hee-tis.atlassian.net/browse/TD-4204
Description for html resource is enabled
**_Before code change:_**
-----
I have:
> TD-4204: Description for html resource is enabled

- AdminUI/LearningHub.Nhs.AdminUI/Scripts/vuesrc/MKPlayerConfigEnum.ts
- AdminUI/LearningHub.Nhs.AdminUI/Scripts/vuesrc/content/cmsPageRow.vue
- LearningHub.Nhs.WebUI/Scripts/vuesrc/MKPlayerConfigEnum.ts
- LearningHub.Nhs.WebUI/Scripts/vuesrc/contribute-resource/components/MKIOVideoPlayer.vue
- LearningHub.Nhs.WebUI/Scripts/vuesrc/resource/ResourceContent.vue
(https://hee-tis.atlassian.net/browse/TD-4274)
-----
I have:
> Fix for apple player

- WebAPI/LearningHub.Nhs.Database/LearningHub.Nhs.Database.sqlproj
- WebAPI/LearningHub.Nhs.Database/Scripts/Post-Deploy/Scripts/TD-4270_Archive_LogDb.sql
[TD-4270](https://hee-tis.atlassian.net/browse/TD-4270)
script to Archive log db
-----
I have:
[TD-4270]: https://hee-tis.atlassian.net/browse/TD-4270?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> TD-4270 Archive Log Db

- WebAPI/LearningHub.Nhs.Database/Scripts/Post-Deploy/Scripts/TD-4270_Archive_LogDb.sql
> LogDb script update

- WebAPI/LearningHub.Nhs.Repository/LearningHubDbContext.cs
- WebAPI/LearningHub.Nhs.Repository/Resources/BlockCollectionRepository.cs
> Tarus release to test

- WebAPI/LearningHub.Nhs.Repository/LearningHubDbContext.cs
- WebAPI/LearningHub.Nhs.Repository/Resources/BlockCollectionRepository.cs
> merge Taurus changes to master

- LearningHub.Nhs.WebUI/Controllers/Api/HierarchyController.cs
- LearningHub.Nhs.WebUI/Interfaces/ICatalogueService.cs
- LearningHub.Nhs.WebUI/Interfaces/IHierarchyService.cs
- LearningHub.Nhs.WebUI/Scripts/vuesrc/content-structure-admin/contentSearch.vue
- LearningHub.Nhs.WebUI/Scripts/vuesrc/content-structure-admin/contentSearchItem.vue
- LearningHub.Nhs.WebUI/Scripts/vuesrc/content-structure-admin/contentStructure.vue
- LearningHub.Nhs.WebUI/Scripts/vuesrc/content-structure-admin/contentStructureState.ts
- LearningHub.Nhs.WebUI/Scripts/vuesrc/content-structure-admin/treeItem.vue
- LearningHub.Nhs.WebUI/Scripts/vuesrc/data/contentStructure.ts
- LearningHub.Nhs.WebUI/Scripts/vuesrc/models/content-structure/editModeEnum.ts
- LearningHub.Nhs.WebUI/Scripts/vuesrc/models/content-structure/folderNodeModel.ts
- LearningHub.Nhs.WebUI/Scripts/vuesrc/models/content-structure/nodeContentAdminModel.ts
- LearningHub.Nhs.WebUI/Scripts/vuesrc/models/content-structure/nodePathBreakdownItemModel.ts
- LearningHub.Nhs.WebUI/Scripts/vuesrc/models/content-structure/nodePathBreakdownModel.ts
- LearningHub.Nhs.WebUI/Scripts/vuesrc/models/content-structure/nodePathDisplayVersionModel.ts
- LearningHub.Nhs.WebUI/Scripts/vuesrc/models/content-structure/resourceReferenceDisplayVersionModel.ts
- LearningHub.Nhs.WebUI/Services/CatalogueService.cs
- LearningHub.Nhs.WebUI/Services/HierarchyService.cs
https://hee-tis.atlassian.net/browse/TD-4291
Content referencing implementation in Web UI
-----
I have:
> TD-4291: Implement Code changes in Web UI-Catalogue Administrator screen

- LearningHub.Nhs.WebUI/Controllers/OpenAthensController.cs
- WebAPI/LearningHub.Nhs.Database/Tables/Resource/ExternalReference.sql
- WebAPI/LearningHub.Nhs.Database/Tables/Resource/ScormResourceVersion.sql
- WebAPI/LearningHub.Nhs.Database/Tables/Resource/ScormResourceVersionManifest.sql
- WebAPI/LearningHub.Nhs.Repository/Resources/BlockCollectionRepository.cs
> Merge   RC changes to scoripus

- LearningHub.Nhs.WebUI/Controllers/ResourceController.cs
_TD-[4205](https://hee-tis.atlassian.net/browse/TD-4205?atlOrigin=eyJpIjoiNWIwMzViNmJhYjlhNDlmN2I2ZDc1YjNjNzQ3NWE4M2UiLCJwIjoiaiJ9)_
_User authentication check is added before recording resource activity for Article/Image which was missing earlier and was recording against user id 4 when user is not logged in._
-----
I have:
> TD-4205: Added user authentication check before recording Article/Image resource activity.

- LearningHub.Nhs.WebUI/Views/Home/_CmsVideo.cshtml
- LearningHub.Nhs.WebUI/wwwroot/css/mkplayer-ui.css
https://hee-tis.atlassian.net/browse/TD-4275
-----
I have:
> Checking in landing page and testing whether the subtitle works

- AdminUI/LearningHub.Nhs.AdminUI/Views/Catalogue/Edit.cshtml
https://hee-tis.atlassian.net/browse/TD-3308
Fixed the issues with the JavaScript formatting.
-----
I have:
> TD-3308 : Fixed the issue with the javascript formatting.

- LearningHub.Nhs.WebUI/Models/Bookmark/EditBookmarkViewModel.cs
https://hee-tis.atlassian.net/browse/TD-3951
Corrected the error messages
-----
I have:
> TD-3951: Corrected the error messages

- WebAPI/LearningHub.Nhs.Database/Scripts/Post-Deploy/Scripts/TD-4270_Archive_LogDb.sql
> archive script update

- AdminUI/LearningHub.Nhs.AdminUI/LearningHub.Nhs.AdminUI.csproj
- LearningHub.Nhs.WebUI/LearningHub.Nhs.WebUI.csproj
- WebAPI/LearningHub.Nhs.API/LearningHub.Nhs.Api.csproj
- WebAPI/LearningHub.Nhs.Api.Shared/LearningHub.Nhs.Api.Shared.csproj
- WebAPI/LearningHub.Nhs.Api.UnitTests/LearningHub.Nhs.Api.UnitTests.csproj
- WebAPI/LearningHub.Nhs.Repository.Interface/LearningHub.Nhs.Repository.Interface.csproj
- WebAPI/LearningHub.Nhs.Repository/LearningHub.Nhs.Repository.csproj
- WebAPI/LearningHub.Nhs.Services.Interface/LearningHub.Nhs.Services.Interface.csproj
- WebAPI/LearningHub.Nhs.Services.UnitTests/LearningHub.Nhs.Services.UnitTests.csproj
- WebAPI/LearningHub.Nhs.Services/LearningHub.Nhs.Services.csproj
- WebAPI/MigrationTool/LearningHub.Nhs.Migration.ConsoleApp/LearningHub.Nhs.Migration.ConsoleApp.csproj
- WebAPI/MigrationTool/LearningHub.Nhs.Migration.Interface/LearningHub.Nhs.Migration.Interface.csproj
- WebAPI/MigrationTool/LearningHub.Nhs.Migration.Models/LearningHub.Nhs.Migration.Models.csproj
- WebAPI/MigrationTool/LearningHub.Nhs.Migration.Staging.Repository/LearningHub.Nhs.Migration.Staging.Repository.csproj
- WebAPI/MigrationTool/LearningHub.Nhs.Migration.UnitTests/LearningHub.Nhs.Migration.UnitTests.csproj
- WebAPI/MigrationTool/LearningHub.Nhs.Migration/LearningHub.Nhs.Migration.csproj
_TD-###_
Model Version updated for CI
-----
I have:
> Model Version updated

- LearningHub.Nhs.WebUI/Controllers/BookmarkController.cs
https://hee-tis.atlassian.net/browse/TD-3951
Error message correction in the bookmark screens
-----
I have:
> TD-3951: Bookmark screen error messages

- LearningHub.Nhs.WebUI/Controllers/Api/HierarchyController.cs
- LearningHub.Nhs.WebUI/Interfaces/IHierarchyService.cs
- LearningHub.Nhs.WebUI/Scripts/vuesrc/constants.ts
- LearningHub.Nhs.WebUI/Scripts/vuesrc/content-structure-admin/contentSearch.vue
- LearningHub.Nhs.WebUI/Scripts/vuesrc/content-structure-admin/contentSearchItem.vue
- LearningHub.Nhs.WebUI/Scripts/vuesrc/content-structure-admin/contentStructure.vue
- LearningHub.Nhs.WebUI/Scripts/vuesrc/content-structure-admin/contentStructureState.ts
- LearningHub.Nhs.WebUI/Scripts/vuesrc/content-structure-admin/treeItem.vue
- LearningHub.Nhs.WebUI/Scripts/vuesrc/data/contentStructure.ts
- LearningHub.Nhs.WebUI/Scripts/vuesrc/models/content-structure/nodeContentAdminModel.ts
- LearningHub.Nhs.WebUI/Services/HierarchyService.cs
https://hee-tis.atlassian.net/browse/TD-4291
External referencing implemented in Catalague/manage interface
-----
I have:
> TD-4291: External referencing implemented.

- LearningHub.Nhs.WebUI/Views/Shared/_Breadcrumbs.cshtml
_TD-3703
mobile view issue
-----
I have:
> TD-3703-Mobile view Fixes

- LearningHub.Nhs.WebUI/Views/Shared/_Breadcrumbs.cshtml
_TD-3703
defect Fix
-----
I have:
> TD-3703-Fixes-For URL-Changed into Titile 

- AdminUI/LearningHub.Nhs.AdminUI/Controllers/api/HierarchyController.cs
- AdminUI/LearningHub.Nhs.AdminUI/Interfaces/IHierarchyService.cs
- AdminUI/LearningHub.Nhs.AdminUI/Scripts/vuesrc/content-structure/contentStructure.vue
- AdminUI/LearningHub.Nhs.AdminUI/Scripts/vuesrc/content-structure/contentStructureState.ts
- AdminUI/LearningHub.Nhs.AdminUI/Scripts/vuesrc/content-structure/treeItem.vue
- AdminUI/LearningHub.Nhs.AdminUI/Scripts/vuesrc/data/contentStructure.ts
- AdminUI/LearningHub.Nhs.AdminUI/Services/HierarchyService.cs
- LearningHub.Nhs.WebUI/Controllers/Api/HierarchyController.cs
- LearningHub.Nhs.WebUI/Interfaces/IHierarchyService.cs
- LearningHub.Nhs.WebUI/Scripts/vuesrc/content-structure-admin/contentStructure.vue
- LearningHub.Nhs.WebUI/Scripts/vuesrc/content-structure-admin/contentStructureState.ts
- LearningHub.Nhs.WebUI/Scripts/vuesrc/content-structure-admin/treeItem.vue
- LearningHub.Nhs.WebUI/Scripts/vuesrc/data/contentStructure.ts
- LearningHub.Nhs.WebUI/Services/HierarchyService.cs
- WebAPI/LearningHub.Nhs.API/Controllers/HierarchyController.cs
- WebAPI/LearningHub.Nhs.Database/LearningHub.Nhs.Database.sqlproj
- WebAPI/LearningHub.Nhs.Database/Scripts/Post-Deploy/Scripts/Content_Referencing_DataSetup.sql
- WebAPI/LearningHub.Nhs.Database/Stored Procedures/Hierarchy/HierarchyEditPublish.sql
- WebAPI/LearningHub.Nhs.Database/Stored Procedures/Hierarchy/HierarchyEditRemoveReferences.sql
- WebAPI/LearningHub.Nhs.Repository.Interface/Hierarchy/IHierarchyEditRepository.cs
- WebAPI/LearningHub.Nhs.Repository/Hierarchy/HierarchyEditRepository.cs
- WebAPI/LearningHub.Nhs.Services.Interface/IHierarchyService.cs
- WebAPI/LearningHub.Nhs.Services/HierarchyService.cs
[_TD-###_](https://hee-tis.atlassian.net/browse/TD-4396)
Implemented the logic to remove the references to be implemented 
-----
I have:
> TD-4396: Removal of references to be implemented

- WebAPI/LearningHub.Nhs.Services/MyLearningService.cs
https://hee-tis.atlassian.net/browse/TD-4389
Fixed the issue with the certificate badge not appearing on the certificate.
-----
I have:
> TD-4389: Certificate badge not appearing on certificate

- AdminUI/LearningHub.Nhs.AdminUI/Scripts/vuesrc/content-structure/contentSearchItem.vue
- AdminUI/LearningHub.Nhs.AdminUI/Scripts/vuesrc/content-structure/contentStructureState.ts
- AdminUI/LearningHub.Nhs.AdminUI/Scripts/vuesrc/content-structure/treeItem.vue
- AdminUI/LearningHub.Nhs.AdminUI/Scripts/vuesrc/models/content-structure/nodeContentAdminModel.ts
- LearningHub.Nhs.WebUI/Scripts/vuesrc/content-structure-admin/contentSearch.vue
- LearningHub.Nhs.WebUI/Scripts/vuesrc/content-structure-admin/contentSearchItem.vue
- LearningHub.Nhs.WebUI/Scripts/vuesrc/content-structure-admin/contentStructureState.ts
- LearningHub.Nhs.WebUI/Scripts/vuesrc/content-structure-admin/treeItem.vue
- LearningHub.Nhs.WebUI/Scripts/vuesrc/models/content-structure/nodeContentAdminModel.ts
https://hee-tis.atlassian.net/browse/TD-4398
Circular referencing scenario handled
-----
I have:
> TD-4398: Circular referencing scenario handled

- AdminUI/LearningHub.Nhs.AdminUI/LearningHub.Nhs.AdminUI.csproj
- LearningHub.Nhs.WebUI/LearningHub.Nhs.WebUI.csproj
- WebAPI/LearningHub.Nhs.API/LearningHub.Nhs.Api.csproj
- WebAPI/LearningHub.Nhs.Api.Shared/LearningHub.Nhs.Api.Shared.csproj
- WebAPI/LearningHub.Nhs.Api.UnitTests/LearningHub.Nhs.Api.UnitTests.csproj
- WebAPI/LearningHub.Nhs.Repository.Interface/LearningHub.Nhs.Repository.Interface.csproj
- WebAPI/LearningHub.Nhs.Repository/LearningHub.Nhs.Repository.csproj
- WebAPI/LearningHub.Nhs.Services.Interface/LearningHub.Nhs.Services.Interface.csproj
- WebAPI/LearningHub.Nhs.Services.UnitTests/LearningHub.Nhs.Services.UnitTests.csproj
- WebAPI/LearningHub.Nhs.Services/LearningHub.Nhs.Services.csproj
- WebAPI/MigrationTool/LearningHub.Nhs.Migration.ConsoleApp/LearningHub.Nhs.Migration.ConsoleApp.csproj
- WebAPI/MigrationTool/LearningHub.Nhs.Migration.Interface/LearningHub.Nhs.Migration.Interface.csproj
- WebAPI/MigrationTool/LearningHub.Nhs.Migration.Models/LearningHub.Nhs.Migration.Models.csproj
- WebAPI/MigrationTool/LearningHub.Nhs.Migration.Staging.Repository/LearningHub.Nhs.Migration.Staging.Repository.csproj
- WebAPI/MigrationTool/LearningHub.Nhs.Migration.UnitTests/LearningHub.Nhs.Migration.UnitTests.csproj
- WebAPI/MigrationTool/LearningHub.Nhs.Migration/LearningHub.Nhs.Migration.csproj
> Modelversion update in Dev Branch

- OpenAPI/LearningHub.Nhs.OpenApi.Repositories.Interface/Repositories/IResourceRepository.cs
- OpenAPI/LearningHub.Nhs.OpenApi.Repositories/Repositories/ResourceRepository.cs
- OpenAPI/LearningHub.Nhs.OpenApi.Services.Interface/Services/IResourceService.cs
- OpenAPI/LearningHub.Nhs.OpenApi.Services/Services/ResourceService.cs
- OpenAPI/LearningHub.Nhs.OpenApi.Tests/Controllers/ResourceControllerTests.cs
- OpenAPI/LearningHub.Nhs.OpenApi.Tests/Services/Services/ResourceServiceTests.cs
- OpenAPI/LearningHub.Nhs.OpenApi/Controllers/OpenApiControllerBase.cs
- OpenAPI/LearningHub.Nhs.OpenApi/Controllers/ResourceController.cs
- OpenAPI/LearningHub.Nhs.OpenApi/SwaggerDefinitions/v1.3.0.json
- WebAPI/LearningHub.Nhs.Database/LearningHub.Nhs.Database.sqlproj
- WebAPI/LearningHub.Nhs.Database/Stored Procedures/Resources/GetAchievedCertificatedResourcesWithOptionalPagination.sql
- WebAPI/LearningHub.Nhs.Database/Stored Procedures/Resources/GetMyCertificatesDashboardResources.sql
> Merge activity status INto Dev

- WebAPI/LearningHub.Nhs.Database/Stored Procedures/Hub/RestrictedCatalogueGetSummary.sql
https://hee-tis.atlassian.net/browse/TD-4203
Considering only active users in the page
**_Before code fix:_**
**_After code fix:_**
-----
I have:
> TD-4023: Considering only active users in the page

- .github/workflows/continuous-integration-workflow.yml
- LearningHub.Nhs.WebUI/Views/Home/_CmsVideo.cshtml
- LearningHub.Nhs.WebUI/Views/Shared/Tenant/LearningHub/_Layout.cshtml
> Reverting landing page changes

- AdminUI/LearningHub.Nhs.AdminUI/Views/User/_UserLearningRecord.cshtml
> fTD-3694-Fix in New Linw

- AdminUI/LearningHub.Nhs.AdminUI/LearningHub.Nhs.AdminUI.csproj
- LearningHub.Nhs.WebUI/LearningHub.Nhs.WebUI.csproj
- OpenAPI/LearningHub.Nhs.OpenApi.Repositories.Interface/LearningHub.Nhs.OpenApi.Repositories.Interface.csproj
- OpenAPI/LearningHub.Nhs.OpenApi.Repositories/LearningHub.Nhs.OpenApi.Repositories.csproj
- OpenAPI/LearningHub.Nhs.OpenApi.Tests/LearningHub.Nhs.OpenApi.Tests.csproj
- OpenAPI/LearningHub.Nhs.OpenApi/LearningHub.NHS.OpenAPI.csproj
- WebAPI/LearningHub.Nhs.API/LearningHub.Nhs.Api.csproj
- WebAPI/LearningHub.Nhs.Api.Shared/LearningHub.Nhs.Api.Shared.csproj
- WebAPI/LearningHub.Nhs.Api.UnitTests/LearningHub.Nhs.Api.UnitTests.csproj
- WebAPI/LearningHub.Nhs.Repository.Interface/LearningHub.Nhs.Repository.Interface.csproj
- WebAPI/LearningHub.Nhs.Repository/LearningHub.Nhs.Repository.csproj
- WebAPI/LearningHub.Nhs.Services.Interface/LearningHub.Nhs.Services.Interface.csproj
- WebAPI/LearningHub.Nhs.Services.UnitTests/LearningHub.Nhs.Services.UnitTests.csproj
- WebAPI/LearningHub.Nhs.Services/LearningHub.Nhs.Services.csproj
- WebAPI/MigrationTool/LearningHub.Nhs.Migration.ConsoleApp/LearningHub.Nhs.Migration.ConsoleApp.csproj
- WebAPI/MigrationTool/LearningHub.Nhs.Migration.Interface/LearningHub.Nhs.Migration.Interface.csproj
- WebAPI/MigrationTool/LearningHub.Nhs.Migration.Models/LearningHub.Nhs.Migration.Models.csproj
- WebAPI/MigrationTool/LearningHub.Nhs.Migration.Staging.Repository/LearningHub.Nhs.Migration.Staging.Repository.csproj
- WebAPI/MigrationTool/LearningHub.Nhs.Migration.UnitTests/LearningHub.Nhs.Migration.UnitTests.csproj
- WebAPI/MigrationTool/LearningHub.Nhs.Migration/LearningHub.Nhs.Migration.csproj
> modelversionupdate in arizona

- LearningHub.Nhs.WebUI/Styles/nhsuk/pages/createaccount.scss
- LearningHub.Nhs.WebUI/Views/Account/CreateAccountCountrySearch.cshtml
> Associate error label with target input and add custom error message for Country Search input errors

- LearningHub.Nhs.WebUI/Views/MyLearning/_ActivityTable.cshtml
> Add alternative hidden text to be displayed when certificate is not available

- LearningHub.Nhs.WebUI/Scripts/vuesrc/notification/notification.vue
- LearningHub.Nhs.WebUI/Styles/nhsuk/layout.scss
> Replace Notification page Delete anchor with button

- LearningHub.Nhs.WebUI/Views/Shared/Tenant/LearningHub/_Layout.cshtml
> Remove external footer tag

- LearningHub.Nhs.WebUI/Views/Account/CreateAccountConfirmation.cshtml
- LearningHub.Nhs.WebUI/Views/MyAccount/Index.cshtml
Add non breaking space symbol to symulate space-bar space. Separate names with normal space.
_TD-4177_
-----
I have:
> Add non breaking space symbol to symulate space-bar space. Separate names with normal space.

- LearningHub.Nhs.WebUI/Views/Account/_AccountCreationGradePaging.cshtml
- LearningHub.Nhs.WebUI/Views/Account/_AccountCreationJobRolePaging.cshtml
- LearningHub.Nhs.WebUI/Views/Account/_AccountCreationRegionPaging.cshtml
- LearningHub.Nhs.WebUI/Views/Account/_AccountCreationSpecialtyPaging.cshtml
- LearningHub.Nhs.WebUI/Views/Account/_AccountCreationWorkPlacePaging.cshtml
- LearningHub.Nhs.WebUI/Views/MyAccount/_UserJobRolePaging.cshtml
- LearningHub.Nhs.WebUI/Views/MyAccount/_UserPrimarySpecialtyPaging.cshtml
- LearningHub.Nhs.WebUI/Views/MyAccount/_UserWorkPlacePaging.cshtml
- LearningHub.Nhs.WebUI/Views/MyLearning/_ActivityTablePaging.cshtml
- LearningHub.Nhs.WebUI/Views/Search/_SubmitFeedback.cshtml
> Display pagination landmark only when pagination show is enabled

- LearningHub.Nhs.WebUI/Views/Account/CreateAccountSearchRole.cshtml
> Remove alternative back button for Role search page

- LearningHub.Nhs.WebUI/Styles/nhsuk/pages/resource.scss
> Contain video play button centered within parent boundaries

- LearningHub.Nhs.WebUI/Scripts/vuesrc/mycontributions/mycontributionscardheader.vue
> Remove tabindex

- LearningHub.Nhs.WebUI/Scripts/vuesrc/notification/notification.vue
> Correct notification shevron and elipses color contrast

- AdminUI/LearningHub.Nhs.AdminUI/LearningHub.Nhs.AdminUI.csproj
- LearningHub.Nhs.WebUI/LearningHub.Nhs.WebUI.csproj
- OpenAPI/LearningHub.Nhs.OpenApi.Repositories.Interface/LearningHub.Nhs.OpenApi.Repositories.Interface.csproj
- OpenAPI/LearningHub.Nhs.OpenApi.Repositories/LearningHub.Nhs.OpenApi.Repositories.csproj
- OpenAPI/LearningHub.Nhs.OpenApi.Tests/LearningHub.Nhs.OpenApi.Tests.csproj
- OpenAPI/LearningHub.Nhs.OpenApi/LearningHub.NHS.OpenAPI.csproj
- WebAPI/LearningHub.Nhs.API/LearningHub.Nhs.Api.csproj
- WebAPI/LearningHub.Nhs.Api.Shared/LearningHub.Nhs.Api.Shared.csproj
- WebAPI/LearningHub.Nhs.Api.UnitTests/LearningHub.Nhs.Api.UnitTests.csproj
- WebAPI/LearningHub.Nhs.Repository.Interface/LearningHub.Nhs.Repository.Interface.csproj
- WebAPI/LearningHub.Nhs.Repository/LearningHub.Nhs.Repository.csproj
- WebAPI/LearningHub.Nhs.Services.Interface/LearningHub.Nhs.Services.Interface.csproj
- WebAPI/LearningHub.Nhs.Services.UnitTests/LearningHub.Nhs.Services.UnitTests.csproj
- WebAPI/LearningHub.Nhs.Services/LearningHub.Nhs.Services.csproj
- WebAPI/MigrationTool/LearningHub.Nhs.Migration.ConsoleApp/LearningHub.Nhs.Migration.ConsoleApp.csproj
- WebAPI/MigrationTool/LearningHub.Nhs.Migration.Interface/LearningHub.Nhs.Migration.Interface.csproj
- WebAPI/MigrationTool/LearningHub.Nhs.Migration.Models/LearningHub.Nhs.Migration.Models.csproj
- WebAPI/MigrationTool/LearningHub.Nhs.Migration.Staging.Repository/LearningHub.Nhs.Migration.Staging.Repository.csproj
- WebAPI/MigrationTool/LearningHub.Nhs.Migration.UnitTests/LearningHub.Nhs.Migration.UnitTests.csproj
- WebAPI/MigrationTool/LearningHub.Nhs.Migration/LearningHub.Nhs.Migration.csproj
> modelversionupdate

- AdminUI/LearningHub.Nhs.AdminUI/Controllers/UserGroupController.cs
TD-4693
Code changes made to clear the permission assigned to a user after being added to a new user group in the admin view
-----
I have:
> TD-4693 cache fix

- WebAPI/LearningHub.Nhs.Database/LearningHub.Nhs.Database.sqlproj
- WebAPI/LearningHub.Nhs.Database/Scripts/Post-Deploy/Scripts/TD-4343_RemoveDuplicateUserGroup.sql
_[TD-4343](https://hee-tis.atlassian.net/browse/TD-4343)_
Added script to remove duplicate rows in Hub.UserUserGroup table. 
-----
I have:
[TD-4343]: https://hee-tis.atlassian.net/browse/TD-4343?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> TD-4343: Script to remove duplicate rows in UserUserGroup table

- WebAPI/LearningHub.Nhs.Database/Stored Procedures/Hierarchy/HierarchyEditPublish.sql
> Update Node Resource Deleted status, if the reference is removed.

- LearningHub.Nhs.WebUI/Views/Shared/_ValidationScriptsPartial.cshtml
> TD-4184Make page focus on top-most element with validation error

- AdminUI/LearningHub.Nhs.AdminUI/LearningHub.Nhs.AdminUI.csproj
- LearningHub.Nhs.WebUI/LearningHub.Nhs.WebUI.csproj
- OpenAPI/LearningHub.Nhs.OpenApi.Models/LearningHub.Nhs.OpenApi.Models.csproj
- OpenAPI/LearningHub.Nhs.OpenApi.Services.Interface/LearningHub.Nhs.OpenApi.Services.Interface.csproj
- OpenAPI/LearningHub.Nhs.OpenApi.Services/LearningHub.Nhs.OpenApi.Services.csproj
- WebAPI/LearningHub.Nhs.API/LearningHub.Nhs.Api.csproj
- WebAPI/LearningHub.Nhs.Api.Shared/LearningHub.Nhs.Api.Shared.csproj
- WebAPI/LearningHub.Nhs.Api.UnitTests/LearningHub.Nhs.Api.UnitTests.csproj
- WebAPI/LearningHub.Nhs.Repository.Interface/LearningHub.Nhs.Repository.Interface.csproj
- WebAPI/LearningHub.Nhs.Repository/LearningHub.Nhs.Repository.csproj
- WebAPI/LearningHub.Nhs.Services.Interface/LearningHub.Nhs.Services.Interface.csproj
- WebAPI/LearningHub.Nhs.Services.UnitTests/LearningHub.Nhs.Services.UnitTests.csproj
- WebAPI/LearningHub.Nhs.Services/LearningHub.Nhs.Services.csproj
- WebAPI/MigrationTool/LearningHub.Nhs.Migration.ConsoleApp/LearningHub.Nhs.Migration.ConsoleApp.csproj
- WebAPI/MigrationTool/LearningHub.Nhs.Migration.Interface/LearningHub.Nhs.Migration.Interface.csproj
- WebAPI/MigrationTool/LearningHub.Nhs.Migration.Models/LearningHub.Nhs.Migration.Models.csproj
- WebAPI/MigrationTool/LearningHub.Nhs.Migration.Staging.Repository/LearningHub.Nhs.Migration.Staging.Repository.csproj
- WebAPI/MigrationTool/LearningHub.Nhs.Migration.UnitTests/LearningHub.Nhs.Migration.UnitTests.csproj
- WebAPI/MigrationTool/LearningHub.Nhs.Migration/LearningHub.Nhs.Migration.csproj
> Model Version update for Virgo

- WebAPI/LearningHub.Nhs.Database/LearningHub.Nhs.Database.sqlproj
- WebAPI/LearningHub.Nhs.Database/Scripts/Post-Deploy/Script.PostDeployment.sql
- WebAPI/LearningHub.Nhs.Database/Scripts/Post-Deploy/Scripts/PPSXFileType.sql
https://hee-tis.atlassian.net/browse/TD-4373
-----
I have:
> TD-4373-Allow ppsx file type

- AdminUI/LearningHub.Nhs.AdminUI/Views/Catalogue/Edit.cshtml
- LearningHub.Nhs.WebUI/Scripts/vuesrc/contribute-resource/components/KeyWordsEditor.vue
- LearningHub.Nhs.WebUI/Scripts/vuesrc/contribute/ContentCommon.vue
_[TD-4430](https://hee-tis.atlassian.net/browse/TD-4430)_
Fixed issue on duplicate keywords when keywords with leading white spaces. Also when adding keywords it will be converted to lowercase across the application.
-----
I have:
[TD-4430]: https://hee-tis.atlassian.net/browse/TD-4430?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> TD-4430: Duplicate keywords issue

- LearningHub.Nhs.WebUI/Views/MyAccount/ChangeCurrentRole.cshtml
- LearningHub.Nhs.WebUI/Views/Shared/_ValidationScriptsPartial.cshtml
> Make error message more evident

- WebAPI/LearningHub.Nhs.Database/Scripts/ELFH Database Scripts/Set up LH Tenant.sql
_TD-###_
to fix the build issues
-----
I have:
> excluded unwanted script

- OpenAPI/LearningHub.Nhs.OpenApi.Services/Services/SearchService.cs
https://hee-tis.atlassian.net/browse/TD-2895
fix to display search results with the activity statuses.
-----
I have:
> To fix the issue with the statuses

- WebAPI/LearningHub.Nhs.Database/Stored Procedures/Resources/GetMyInProgressDashboardResources.sql
https://hee-tis.atlassian.net/browse/TD-2895
Fixed the issue with the my learning tray in progress activities
-----
I have:
> Fixed the my learning tray issue

- AdminUI/LearningHub.Nhs.AdminUI/LearningHub.Nhs.AdminUI.csproj
- LearningHub.Nhs.WebUI/LearningHub.Nhs.WebUI.csproj
- OpenAPI/LearningHub.Nhs.OpenApi.Models/LearningHub.Nhs.OpenApi.Models.csproj
- OpenAPI/LearningHub.Nhs.OpenApi.Services/LearningHub.Nhs.OpenApi.Services.csproj
- WebAPI/LearningHub.Nhs.API/LearningHub.Nhs.Api.csproj
- WebAPI/LearningHub.Nhs.Api.Shared/LearningHub.Nhs.Api.Shared.csproj
- WebAPI/LearningHub.Nhs.Api.UnitTests/LearningHub.Nhs.Api.UnitTests.csproj
- WebAPI/LearningHub.Nhs.Repository/LearningHub.Nhs.Repository.csproj
- WebAPI/LearningHub.Nhs.Services.Interface/LearningHub.Nhs.Services.Interface.csproj
- WebAPI/LearningHub.Nhs.Services.UnitTests/LearningHub.Nhs.Services.UnitTests.csproj
- WebAPI/LearningHub.Nhs.Services/LearningHub.Nhs.Services.csproj
- WebAPI/MigrationTool/LearningHub.Nhs.Migration.ConsoleApp/LearningHub.Nhs.Migration.ConsoleApp.csproj
- WebAPI/MigrationTool/LearningHub.Nhs.Migration.Interface/LearningHub.Nhs.Migration.Interface.csproj
- WebAPI/MigrationTool/LearningHub.Nhs.Migration.Models/LearningHub.Nhs.Migration.Models.csproj
- WebAPI/MigrationTool/LearningHub.Nhs.Migration.Staging.Repository/LearningHub.Nhs.Migration.Staging.Repository.csproj
- WebAPI/MigrationTool/LearningHub.Nhs.Migration.UnitTests/LearningHub.Nhs.Migration.UnitTests.csproj
- WebAPI/MigrationTool/LearningHub.Nhs.Migration/LearningHub.Nhs.Migration.csproj
> Update Model Version

- OpenAPI/LearningHub.Nhs.OpenApi.Services.Interface/LearningHub.Nhs.OpenApi.Services.Interface.csproj
- WebAPI/LearningHub.Nhs.Repository.Interface/LearningHub.Nhs.Repository.Interface.csproj
> Model Version Update Tucana

- LearningHub.Nhs.WebUI/Scripts/vuesrc/notification/notifications.vue
- LearningHub.Nhs.WebUI/Views/Account/CreateAccountConfirmation.cshtml
- LearningHub.Nhs.WebUI/Views/Bookmark/Index.cshtml
- LearningHub.Nhs.WebUI/Views/MyAccount/Index.cshtml
…y Bookmarks, My account"
_TD-4193_
-----
I have:
> Correct titles for "Summary List, Notifications, My Bookmarks, My account"

- LearningHub.Nhs.WebUI/Views/Account/CreateAccountProfessionalRegNumber.cshtml
> Update NMC Number field error message

- LearningHub.Nhs.WebUI/Scripts/vuesrc/mycontributions/mycontributions.vue
> Make content of Change Catalogue menu interactive

- LearningHub.Nhs.WebUI/Views/Shared/_NavPartial.cshtml
TD-4197
DIG1405: Button text is not descriptive of purpose
-----
I have:
> TD-4197-DIG1405: Button text is not descriptive of purpose

- AdminUI/LearningHub.Nhs.AdminUI/LearningHub.Nhs.AdminUI.csproj
- LearningHub.Nhs.WebUI/LearningHub.Nhs.WebUI.csproj
- OpenAPI/LearningHub.Nhs.OpenApi.Models/LearningHub.Nhs.OpenApi.Models.csproj
- OpenAPI/LearningHub.Nhs.OpenApi.Services.Interface/LearningHub.Nhs.OpenApi.Services.Interface.csproj
- OpenAPI/LearningHub.Nhs.OpenApi.Services/LearningHub.Nhs.OpenApi.Services.csproj
- WebAPI/LearningHub.Nhs.API/LearningHub.Nhs.Api.csproj
- WebAPI/LearningHub.Nhs.Api.Shared/LearningHub.Nhs.Api.Shared.csproj
- WebAPI/LearningHub.Nhs.Api.UnitTests/LearningHub.Nhs.Api.UnitTests.csproj
- WebAPI/LearningHub.Nhs.Database/Tables/Resource/ResourceVersion.sql
- WebAPI/LearningHub.Nhs.Repository.Interface/LearningHub.Nhs.Repository.Interface.csproj
- WebAPI/LearningHub.Nhs.Repository/LearningHub.Nhs.Repository.csproj
- WebAPI/LearningHub.Nhs.Services.Interface/LearningHub.Nhs.Services.Interface.csproj
- WebAPI/LearningHub.Nhs.Services.UnitTests/LearningHub.Nhs.Services.UnitTests.csproj
- WebAPI/LearningHub.Nhs.Services/LearningHub.Nhs.Services.csproj
- WebAPI/MigrationTool/LearningHub.Nhs.Migration.ConsoleApp/LearningHub.Nhs.Migration.ConsoleApp.csproj
- WebAPI/MigrationTool/LearningHub.Nhs.Migration.Interface/LearningHub.Nhs.Migration.Interface.csproj
- WebAPI/MigrationTool/LearningHub.Nhs.Migration.Models/LearningHub.Nhs.Migration.Models.csproj
- WebAPI/MigrationTool/LearningHub.Nhs.Migration.Staging.Repository/LearningHub.Nhs.Migration.Staging.Repository.csproj
- WebAPI/MigrationTool/LearningHub.Nhs.Migration.UnitTests/LearningHub.Nhs.Migration.UnitTests.csproj
- WebAPI/MigrationTool/LearningHub.Nhs.Migration/LearningHub.Nhs.Migration.csproj
_TD-###_
PR to merge latest RC changes to V1.0.0 (Model class update)
-----
I have:
> Merge RC changes to V1.0.0

- .github/pull_request_template.md
[TD-4992](https://hee-tis.atlassian.net/browse/TD-4992)
Updates the pull request template in line with the changes agreed in the dev team review.
-----
I have:
[TD-4992]: https://hee-tis.atlassian.net/browse/TD-4992?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> TD-4992 Update PR template

- AdminUI/LearningHub.Nhs.AdminUI/Scripts/vuesrc/content/pageSectionToolbar.vue
https://hee-tis.atlassian.net/browse/TD-4944
Design fixes
-----
I have:
> Design fix

- AdminUI/LearningHub.Nhs.AdminUI/Scripts/vuesrc/content/pageSectionToolbar.vue
https://hee-tis.atlassian.net/browse/TD-4944
Design fix
-----
I have:
> Design fixes

- AdminUI/LearningHub.Nhs.AdminUI/wwwroot/css/mkplayer-ui.css
- LearningHub.Nhs.WebUI/wwwroot/css/mkplayer-ui.css
https://hee-tis.atlassian.net/browse/TD-4944
_Design fixes
-----
I have:
> Css fixes for mobile devices

- WebAPI/LearningHub.Nhs.Database/LearningHub.Nhs.Database.sqlproj
https://hee-tis.atlassian.net/browse/TD-5036
Included triggers also into the schema
-----
I have:
> Included triggers into the schema

- LearningHub.Nhs.WebUI/LearningHub.Nhs.WebUI.csproj
- LearningHub.Nhs.WebUI/Views/Shared/Components/DateInput/Default.cshtml
- LearningHub.Nhs.WebUI/Views/Shared/Components/ErrorSummary/Default.cshtml
- LearningHub.Nhs.WebUI/Views/Shared/Components/RadioList/Default.cshtml
> Updated nhs design system model version

- LearningHub.Nhs.WebUI/Views/Shared/Tenant/LearningHub/_Layout.cshtml
_TD-4176
Reverting Old changes -Fixed the same issue as part of Virgo release
-----
I have:
> TD-4176-Reverting Old changes -Fixed the same issue as part of Virgo release

- LearningHub.Nhs.WebUI/Scripts/vuesrc/notification/notification.vue
> TD-4188 -Correct notification shevron and elipses color contrast

- LearningHub.Nhs.WebUI/Scripts/vuesrc/mycontributions/mycontributionscardheader.vue
> TD-4196 Remove tabindex

- LearningHub.Nhs.WebUI/Views/Shared/_NavPartial.cshtml
> TD-4197-Reintroducing changes 

- LearningHub.Nhs.WebUI/Views/Shared/_ValidationScriptsPartial.cshtml
_[TD-5086](https://hee-tis.atlassian.net/browse/TD-5086)_
Fixed console errors on LH landing page
-----
I have:
[TD-5086]: https://hee-tis.atlassian.net/browse/TD-5086?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> TD-5086: Fixed console errors on LH landing page

- LearningHub.Nhs.WebUI/Controllers/AccountController.cs
TD-4192
Removed HttP post call to allow account creation 
-----
I have:
> TD-4192-Removed Httt post call to allow account creation 

- AdminUI/LearningHub.Nhs.AdminUI/Controllers/ResourceController.cs
- AdminUI/LearningHub.Nhs.AdminUI/Views/Resource/Details.cshtml
- AdminUI/LearningHub.Nhs.AdminUI/Views/Resource/_DevIdDetails.cshtml
https://hee-tis.atlassian.net/browse/TD-2396
Implemented the SIT comments in the ticket
-----
I have:
> TD-2396: SIT fixes for the Dev Id implementation.

- LearningHub.Nhs.WebUI/Views/Account/_AccountCreationGradePaging.cshtml
- LearningHub.Nhs.WebUI/Views/Account/_AccountCreationJobRolePaging.cshtml
- LearningHub.Nhs.WebUI/Views/Account/_AccountCreationRegionPaging.cshtml
- LearningHub.Nhs.WebUI/Views/Account/_AccountCreationSpecialtyPaging.cshtml
- LearningHub.Nhs.WebUI/Views/Account/_AccountCreationWorkPlacePaging.cshtml
- LearningHub.Nhs.WebUI/Views/MyAccount/_UserJobRolePaging.cshtml
- LearningHub.Nhs.WebUI/Views/MyAccount/_UserPrimarySpecialtyPaging.cshtml
- LearningHub.Nhs.WebUI/Views/MyAccount/_UserWorkPlacePaging.cshtml
- LearningHub.Nhs.WebUI/Views/MyLearning/_ActivityTablePaging.cshtml
https://hee-tis.atlassian.net/browse/TD-4179
Removed pagination landmark if no pages.
-----
I have:
> Td-4179: DIG253: A landmark is present on the page but it has no content

- AdminUI/LearningHub.Nhs.AdminUI/Controllers/ResourceController.cs
https://hee-tis.atlassian.net/browse/TD-2396
Removed leading/trailing end spaces when user adds Dev ID’s with spaces.
-----
I have:
> TD-2396: Dev Id implementaion SIT fixes

- LearningHub.Nhs.WebUI/Views/Account/CreateAccountConfirmation.cshtml
- LearningHub.Nhs.WebUI/Views/LoginWizard/AccountConfirmation.cshtml
_[TD-4177](https://hee-tis.atlassian.net/browse/TD-4177)_
Changed text content accordingly for screen reader.
-----
I have:
[TD-4177]: https://hee-tis.atlassian.net/browse/TD-4177?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> TD-4177: Changed text content accordingly for screen reader

- LearningHub.Nhs.WebUI/Views/Shared/Components/DateInput/Default.cshtml
- LearningHub.Nhs.WebUI/Views/Shared/Components/ErrorSummary/Default.cshtml
- LearningHub.Nhs.WebUI/Views/Shared/Components/RadioList/Default.cshtml
> Revert Design Changes caused  by commit 

- LearningHub.Nhs.WebUI/LearningHub.Nhs.WebUI.csproj
TD-4180
updated view component version.
-----
I have:
> TD-4180: updated view component version

- LearningHub.Nhs.WebUI/Views/Catalogue/AllCatalogue.cshtml
TD-4193
needs to change the second word starting letter to upper case
-----
I have:
> TD-4193-needs to change the second word starting letter to upper case

- AdminUI/LearningHub.Nhs.AdminUI/Views/Shared/_Layout.cshtml
- LearningHub.Nhs.WebUI/Views/Shared/Tenant/LearningHub/_Layout.cshtml
- ReportAPI/LearningHub.Nhs.ReportApi/ServiceCollectionExtension.cs
- WebAPI/LearningHub.Nhs.API/ServiceCollectionExtension.cs
> Merge Build Number Changes to RC

- LearningHub.Nhs.WebUI/Scripts/vuesrc/mycontributions/gridcomponent.vue
- LearningHub.Nhs.WebUI/Scripts/vuesrc/mycontributions/mycontributions.vue
_[TD-4196](https://hee-tis.atlassian.net/browse/TD-4196)_
Fixed focus issue on my contributions page
-----
I have:
[TD-4196]: https://hee-tis.atlassian.net/browse/TD-4196?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> TD-4196: Fixed focus issue on my contributions page

- ReportAPI/LearningHub.Nhs.ReportApi.Services.UnitTests/PdfReportServicesTests.cs
Auto mapper issue fixed after framework upgrade
-----
I have:
Either:
Or:
> Automapper issue fixed after framework upgrade

- WebAPI/LearningHub.Nhs.API/Controllers/UserGroupController.cs
SIT issue: User group creation was failing after .net framework upgrade
Fixed the issue with the User group creation after .net framework upgrade
-----
I have:
Either:
Or:
> Fixed the issue with the User group creation from the Admin UI

- LearningHub.Nhs.WebUI/Scripts/vuesrc/notification/notification.vue
TD-5304
elements that behave as a button use button markup.
-----
I have:
Either:
Or:
> TD-5304-Notifications Page - Anchors are used for buttons

- LearningHub.Nhs.WebUI/Views/Shared/Components/NavigationItems/Searchbar.cshtml
- LearningHub.Nhs.WebUI/Views/Shared/_NavPartial.cshtml
[TD-5299](https://hee-tis.atlassian.net/browse/TD-5299)
Removed focus on visually hidden content
-----
I have:
Either:
Or:
[TD-5299]: https://hee-tis.atlassian.net/browse/TD-5299?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> TD-5299: Removed focus on visually hidden content

- AdminUI/LearningHub.Nhs.AdminUI/Views/Catalogue/Edit.cshtml
TD-4465
AdminUI and Contribute resource page has Console errors and warnings
-----
I have:
> TD-4465-AdminUI and Contribute resource page has Console errors and warnings

- WebAPI/LearningHub.Nhs.API/LearningHub.Nhs.Api.csproj
- WebAPI/LearningHub.Nhs.Services/LearningHub.Nhs.Services.csproj
Downgrading System.IdentityModel.Tokens.Jwt to fix the error in Test Env
> downgrading System.IdentityModel.Tokens.Jwt to fix the error in Test Env

- LearningHub.Nhs.WebUI/Controllers/Api/ResourceController.cs
- LearningHub.Nhs.WebUI/Services/FileService.cs
[TD-5348]([TD-5348](https://hee-tis.atlassian.net/browse/TD-5348))
This is expected to keep connection alive in the gateway. 
This works locally but needs to be validated in the azure test environment.
-----
I have:
Either:
Or:
[TD-5348]: https://hee-tis.atlassian.net/browse/TD-5348?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[TD-5348]: https://hee-tis.atlassian.net/browse/TD-5348?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> TD-5348 stream files with keep alive.

- LearningHub.Nhs.WebUI/Controllers/Api/ResourceController.cs
- LearningHub.Nhs.WebUI/Services/FileService.cs
> Revert code changes

- LearningHub.Nhs.WebUI/Views/Account/CreateAccountRegistrationInformation.cshtml
_[TD-4934](https://hee-tis.atlassian.net/browse/TD-4934)_
Rewording of General Users introduction sentence.
Before
After
-----
I have:
[TD-4934]: https://hee-tis.atlassian.net/browse/TD-4934?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> TD-4934: Rewording of General Users introduction sentence

- LearningHub.Nhs.WebUI/Views/Account/CreateAccountRegistrationInformation.cshtml
_[TD-4964](https://hee-tis.atlassian.net/browse/TD-4964)_
Rewording of list of additional required information
Before
After
-----
I have:
[TD-4964]: https://hee-tis.atlassian.net/browse/TD-4964?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> TD-4964:  Rewording of list of additional required information

- LearningHub.Nhs.WebUI/Views/Account/CreateAccountEmailVerification.cshtml
_[TD-4968](https://hee-tis.atlassian.net/browse/TD-4968)_
Reword statement "Ideally you should provide a work email address so that your registration results in the most appropriate access."
Before
After
-----
I have:
[TD-4968]: https://hee-tis.atlassian.net/browse/TD-4968?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> TD-4968: Reword statement "Ideally you should provide a work email address so that your registration results in the most appropriate access."

- LearningHub.Nhs.WebUI/Views/Policies/AcceptableUsePolicy.cshtml
[TD-5303](https://hee-tis.atlassian.net/browse/TD-5303)
Restructured Acceptable use policy page
-----
I have:
Either:
Or:
[TD-5303]: https://hee-tis.atlassian.net/browse/TD-5303?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> TD-5303: Restructured Acceptable use policy page

- WebAPI/LearningHub.Nhs.API/Controllers/CatalogueController.cs
https://hee-tis.atlassian.net/browse/TD-5372
Fixed the issue with the catalogue update
-----
I have:
Either:
Or:
> TD-5372 : Unable to Edit Catalogue in Prod Env

- OpenAPI/LearningHub.Nhs.OpenApi/Startup.cs
- ReportAPI/LearningHub.Nhs.ReportApi/Program.cs
- WebAPI/LearningHub.Nhs.API/Program.cs
https://hee-tis.atlassian.net/browse/TD-3732
Added Missing Security Headers in all API solutions.
-----
I have:
Either:
Or:
> TD-3732: Missing Security Headers

- WebAPI/LearningHub.Nhs.Database/Scripts/ELFH Database Scripts/Update LH email content.sql
[TD-5001](https://hee-tis.atlassian.net/browse/TD-5001)
Word support placement
-----
I have:
Either:
Or:
[TD-5001]: https://hee-tis.atlassian.net/browse/TD-5001?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> TD-5001: Word support placement

- WebAPI/LearningHub.Nhs.Database/Scripts/ELFH Database Scripts/Update LH email content.sql
TD-5001
Automatic email - Thank you for creating an account on the Learning Hub
-----
I have:
Either:
Or:
> TD-5001-Automatic email - Thank you for creating an account on the Learning Hub

- OpenAPI/LearningHub.Nhs.OpenApi/Startup.cs
- ReportAPI/LearningHub.Nhs.ReportApi/Program.cs
- WebAPI/LearningHub.Nhs.API/Program.cs
https://hee-tis.atlassian.net/browse/TD-3733
Modified the security headers
-----
I have:
Either:
Or:
> TD-3733-TD-3733:Information Disclosures

- LearningHub.Nhs.WebUI.AutomatedUiTests/AccessibilityTests/AccessibilityTestsBase.cs
- LearningHub.Nhs.WebUI.AutomatedUiTests/AccessibilityTests/BasicAccessibilityTests.cs
- LearningHub.Nhs.WebUI.AutomatedUiTests/AccessibilityTests/BasicAuthenticatedAccessibilityTests.cs
- LearningHub.Nhs.WebUI.AutomatedUiTests/AccessibilityTests/BookmarksTests.cs
- LearningHub.Nhs.WebUI.AutomatedUiTests/AccessibilityTests/CatalogueFolderContentTests.cs
- LearningHub.Nhs.WebUI.AutomatedUiTests/AccessibilityTests/CreateAccountTests.cs
- LearningHub.Nhs.WebUI.AutomatedUiTests/AccessibilityTests/DashboardTests.cs
- LearningHub.Nhs.WebUI.AutomatedUiTests/AccessibilityTests/MyAccountAccessibiltyTests.cs
- LearningHub.Nhs.WebUI.AutomatedUiTests/AccessibilityTests/MyContributionsTests.cs
- LearningHub.Nhs.WebUI.AutomatedUiTests/AccessibilityTests/ResourcePagesTests.cs
- LearningHub.Nhs.WebUI.AutomatedUiTests/AccessibilityTests/SearchResultsTests.cs
- LearningHub.Nhs.WebUI.AutomatedUiTests/GlobalSuppressions.cs
- LearningHub.Nhs.WebUI.AutomatedUiTests/LearningHub.Nhs.WebUI.AutomatedUiTests.csproj
- LearningHub.Nhs.WebUI.AutomatedUiTests/SeleniumServerFactory.cs
- LearningHub.Nhs.WebUI.AutomatedUiTests/TestFixtures/AccessibilityTestsFixture.cs
- LearningHub.Nhs.WebUI.AutomatedUiTests/TestFixtures/AuthenticatedAccessibilityTestsFixture.cs
- LearningHub.Nhs.WebUI.AutomatedUiTests/TestHelpers/ConfigurationHelper.cs
- LearningHub.Nhs.WebUI.AutomatedUiTests/TestHelpers/DriverHelper.cs
- LearningHub.Nhs.WebUI.AutomatedUiTests/TestHelpers/LoginHelper.cs
- LearningHub.Nhs.WebUI.AutomatedUiTests/appsettings.json
- LearningHub.Nhs.WebUI.sln
- LearningHub.Nhs.WebUI/Views/Account/CreateAccountPrimarySpecialty.cshtml
- LearningHub.Nhs.WebUI/Views/Account/CreateAccountPrimarySpecialtySelection.cshtml
- LearningHub.Nhs.WebUI/Views/Bookmark/Move.cshtml
- LearningHub.Nhs.WebUI/Views/Bookmark/_BookmarkItem.cshtml
- LearningHub.Nhs.WebUI/Views/MyAccount/ChangeLastName.cshtml
- LearningHub.Nhs.WebUI/Views/Shared/Components/NavigationItems/Searchbar.cshtml
- LearningHub.Nhs.WebUI/Views/Shared/_NavPartial.cshtml
> Merge release/accessibility to English Ivy 1.3.1

- LearningHub.Nhs.WebUI/Controllers/HomeController.cs
Fixed the issue with the logout
-----
I have:
Either:
Or:
> Fixed the issue with logout

- AdminUI/LearningHub.Nhs.AdminUI/Views/Resource/Details.cshtml
TD-5146
fixed unknown error when accessing the draft scorm elearning resources from Admin section
-----
I have:
Either:
Or:
> TD-5146-Showing unknown error when accessing the draft scorm elearning resources from Admin section

- OpenAPI/LearningHub.Nhs.OpenApi.Repositories/Repositories/ResourceRepository.cs
- OpenAPI/LearningHub.Nhs.OpenApi.Repositories/Repositories/RoleUserGroupRepository.cs
- OpenAPI/LearningHub.Nhs.OpenApi.Services/Services/SearchService.cs
- OpenAPI/LearningHub.Nhs.OpenApi/Controllers/ResourceController.cs
[TD-5118](https://hee-tis.atlassian.net/browse/TD-5118)
route fix for GetResourceReferenceByOriginalId which conflicted with GetResource controller method
Removal of duplicated dbcontext which resulted in a null exception
Fix to properly populate the  findwise search endpoint. (*to be addressed in the WebAPI in a separate ticket)
-----
I have:
Either:
Or:
[TD-5118]: https://hee-tis.atlassian.net/browse/TD-5118?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Code fix for expansion of our OpenAPI project

- WebAPI/LearningHub.Nhs.API/appsettings.json
[TD-5170](https://hee-tis.atlassian.net/browse/TD-5170)
Corrected the support team url.
-----
I have:
Either:
Or:
[TD-5170]: https://hee-tis.atlassian.net/browse/TD-5170?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> TD-5170: Corrected the support team url.

- WebAPI/LearningHub.Nhs.Database/LearningHub.Nhs.Database.sqlproj
https://hee-tis.atlassian.net/browse/TD-5492
Upgraded .NET Framework Version For Database Project from 4.5.2 to 4.8
-----
I have:
Either:
Or:
> .net framework upgraded for Database project

- WebAPI/LearningHub.Nhs.Database/LearningHub.Nhs.Database.sqlproj
- WebAPI/LearningHub.Nhs.Database/Stored Procedures/External/ExternalSystemUserCreate.sql
https://hee-tis.atlassian.net/browse/TD-5407
Implemented a fix to avoid SQL exception on LinkExistingUserToSso method.- Created a stored procedure to insert the data in to the table instead of EF call.
-----
I have:
Either:
Or:
> TD-5407: Created new SP to fix the SQL exception

- OpenAPI/LearningHub.Nhs.OpenApi/SwaggerDefinitions/v1.3.0.json
[TD-5118](https://hee-tis.atlassian.net/browse/TD-5118)
The swagger documentation was updated.
-----
I have:
Either:
Or:
[TD-5118]: https://hee-tis.atlassian.net/browse/TD-5118?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> TD-5118 documentation update

- AdminUI/LearningHub.Nhs.AdminUI/package-lock.json
- AdminUI/LearningHub.Nhs.AdminUI/package.json
- LearningHub.Nhs.WebUI/package-lock.json
- LearningHub.Nhs.WebUI/package.json
> Automatic version update dependabot T  to RC

- LearningHub.Nhs.WebUI/Services/MoodleHttpClient.cs
- LearningHub.Nhs.WebUI/Views/Home/_CourseEnrolled.cshtml
> removed the hardcoded url in moodle entrolled course

- WebAPI/MigrationTool/LearningHub.Nhs.Migration.Staging.Database/LearningHub.Nhs.Migration.Staging.Database.sqlproj
https://hee-tis.atlassian.net/browse/TD-5492
Upgraded .NET Framework Version For Database Project to 4.8
-----
I have:
Either:
Or:
> Updated the target framework version to 4.8

- LearningHub.Nhs.WebUI/Views/Policies/Index.cshtml
https://hee-tis.atlassian.net/browse/TD-5182
Corrected the title
-----
I have:
Either:
Or:
> Corrected the title

- LearningHub.Nhs.WebUI/Scripts/vuesrc/contribute/ContentCommon.vue
- LearningHub.Nhs.WebUI/Styles/nhsuk/common.scss
[TD-5608](https://hee-tis.atlassian.net/browse/TD-5608)
Radio buttons / rating stars selection alignment issue fixed
-----
I have:
Either:
Or:
[TD-5608]: https://hee-tis.atlassian.net/browse/TD-5608?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> TD-5608: Radio buttons / rating stars selection misaligned

- AdminUI/LearningHub.Nhs.AdminUI/Views/Resource/Details.cshtml
- LearningHub.Nhs.WebUI/Controllers/MyAccountController.cs
- WebAPI/LearningHub.Nhs.Services/MyLearningService.cs
Reverts TechnologyEnhancedLearning/LearningHub.Nhs.WebUI#1144
> Release v1.5.1 grass lily  To Test"  from RC after Hotfix release

- OpenAPI/LearningHub.Nhs.OpenApi/Controllers/UserController.cs
https://hee-tis.atlassian.net/browse/TD-5560
moved my learning menu item to the second position in the menu item list
-----
I have:
Either:
Or:
> Changed the LH menu item order

- LearningHub.Nhs.WebUI/Controllers/HomeController.cs
[TD-5715](https://hee-tis.atlassian.net/browse/TD-5715)
Fixed the issue with the My accessed learning tray - navigation link.
-----
I have:
Either:
Or:
[TD-5715]: https://hee-tis.atlassian.net/browse/TD-5715?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> TD-5715: My accessed learning tray - navigation link doesn't work-Production

- LearningHub.Nhs.WebUI/Controllers/Api/UserController.cs
- LearningHub.Nhs.WebUI/Scripts/vuesrc/data/user.ts
[TD-5708](https://hee-tis.atlassian.net/browse/TD-5708)
Fixed the issue with password validation for passwords containing special characters like '%', '&', etc."
-----
I have:
Either:
Or:
[TD-5708]: https://hee-tis.atlassian.net/browse/TD-5708?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> TD-5708: Password validation is failing for the users with password '&;

- OpenAPI/LearningHub.Nhs.OpenApi.Services.Interface/Services/IResourceService.cs
- OpenAPI/LearningHub.Nhs.OpenApi.Services/Services/ResourceService.cs
- OpenAPI/LearningHub.Nhs.OpenApi/Controllers/ResourceController.cs
[TD-5499](https://hee-tis.atlassian.net/browse/TD-5499)
-----
I have:
Either:
Or:
[TD-5499]: https://hee-tis.atlassian.net/browse/TD-5499?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Addition of a missing endpoint

- LearningHub.Nhs.WebUI/Services/UserGroupService.cs
Reverted the commented code
-----
I have:
Either:
Or:
> Reverted the commented code

- OpenAPI/LearningHub.Nhs.OpenApi/SwaggerDefinitions/v1.3.0.json
> Updated Swagger.json

- OpenAPI/LearningHub.Nhs.OpenApi.Services.Interface/Services/ICatalogueService.cs
- OpenAPI/LearningHub.Nhs.OpenApi.Services/Services/CatalogueService.cs
- OpenAPI/LearningHub.Nhs.OpenApi/Controllers/CatalogueController.cs
> Reverted Messaging  Service changes from TD-5490-Merged Back latest

- LearningHub.Nhs.WebUI/Views/Home/_ResourceTray.cshtml
TD-5700-
[TD-5700-Reorder resource tabs on LH home page
1.Highly rated
2.Recently Added
3.Most accessed
-----
I have:
- [] Written or updated tests for the changes (accessibility ui tests for views, tests for controller, data services, services, view models created or modified) and made sure all tests are passing
Either:
Or:
> TD-5700-Reorder resource tabs on LH home page

- LearningHub.Nhs.WebUI/Styles/nhsuk/layout.scss
- LearningHub.Nhs.WebUI/Views/MyAccount/Index.cshtml
- LearningHub.Nhs.WebUI/Views/MyLearning/Index.cshtml
- LearningHub.Nhs.WebUI/Views/Shared/Tenant/LearningHub/_Layout.cshtml
Updated breadcrumb to be in line with the figma views
My Account
My Learning activities
-----
I have:
Either:
Or:
> TD-5863 header breadcrumb changes

- LearningHub.Nhs.WebUI/Scripts/vuesrc/contribute-resource/ContributeLocationTab.vue
- LearningHub.Nhs.WebUI/Scripts/vuesrc/contribute-resource/components/CatalogueView.vue
[TD-5892](https://hee-tis.atlassian.net/browse/TD-5892)
Removed the text
-----
I have:
Either:
Or:
[TD-5892]: https://hee-tis.atlassian.net/browse/TD-5892?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Removed  text

- LearningHub.Nhs.WebUI/Scripts/vuesrc/contribute-resource/ContributeLocationTab.vue
- LearningHub.Nhs.WebUI/Scripts/vuesrc/contribute/ContentCommon.vue
[TD-5892](https://hee-tis.atlassian.net/browse/TD-5892)
Issue fixed for the catalogue creation.
-----
I have:
Either:
Or:
[TD-5892]: https://hee-tis.atlassian.net/browse/TD-5892?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> TD-5892: bug fix for the new resource creation

- LearningHub.Nhs.WebUI/Scripts/vuesrc/contribute/ContentCommon.vue
[TD-5892](https://hee-tis.atlassian.net/browse/TD-5892)
There was an issue where the catalogue section was not visible for users with only one catalogue. This issue has been fixed
-----
I have:
Either:
Or:
[TD-5892]: https://hee-tis.atlassian.net/browse/TD-5892?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> TD-5892: bug fix

- LearningHub.Nhs.WebUI/Views/Catalogue/Index.cshtml
[TD-5916](https://hee-tis.atlassian.net/browse/TD-5916)
System Administrators user group are able to access and launch restricted resources even if they do not belong to the user groups set up in the restricted catalogue. 
**Non Admin**
**Admin**
-----
I have:
Either:
Or:
[TD-5916]: https://hee-tis.atlassian.net/browse/TD-5916?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> TD-5916: Catalogue access not working

- WebAPI/LearningHub.Nhs.Database/Stored Procedures/Activity/GetUserRecentLearningActivities.sql
- WebAPI/LearningHub.Nhs.Database/Stored Procedures/Activity/GetUsersLearningHistory.sql
- WebAPI/LearningHub.Nhs.Database/Stored Procedures/Activity/GetUsersLearningHistory_Search.sql
Fixed the syntax issues with in the sp.
-----
I have:
Either:
Or:
> Fixed the syntax issues with in the sp

- .github/workflows/continuous-integration-workflow.yml
- .gitignore
- nuget.config.cicd
- nuget.config.template
[TD-6114](https://hee-tis.atlassian.net/browse/TD-6114)
Adding Nuget.config.cicd to pipeline
Adding steps to continous-integration-workflow.yml
should still use old nuget feed if nuget.config not there
Will need some bits removing later once nuget.config has worked its way through the pipeline
(if we made the changes straight away the current azure pipeline would break )
[TD-6114]: https://hee-tis.atlassian.net/browse/TD-6114?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> TD-6116 Workflow and Nuget update

- LearningHub.Nhs.WebUI/Helpers/ViewActivityHelper.cs
- LearningHub.Nhs.WebUI/Views/MyLearning/LearningCertificate.cshtml
https://hee-tis.atlassian.net/browse/TD-6208
Updated method displaying status on certificate
-----
I have:
Either:
Or:
> TD-6208 Certificate Status update

- OpenAPI/LearningHub.Nhs.OpenApi.Services/Services/MyLearningService.cs
https://hee-tis.atlassian.net/browse/TD-6213
efcore query fix 
-----
I have:
Either:
Or:
> TD-6213 Informal assessment ef query fix

- LearningHub.Nhs.WebUI/Helpers/UtilityHelper.cs
TD-6161
_Courses are showing as files in search results
-----
I have:
Either:
Or:
> TD-6161-Courses are showing as files in search results

- LearningHub.Nhs.WebUI/Styles/nhsuk/layout.scss
- LearningHub.Nhs.WebUI/Views/Shared/Components/SideNav/Default.cshtml
[TD-5762](https://hee-tis.atlassian.net/browse/TD-5762)
Fixed issues on left hand navigation
-----
I have:
Either:
Or:
[TD-5762]: https://hee-tis.atlassian.net/browse/TD-5762?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> TD-5762: Fixed issues on left hand navigation

- AdminUI/LearningHub.Nhs.AdminUI/LearningHub.Nhs.AdminUI.csproj
- LearningHub.Nhs.WebUI.AutomatedUiTests/LearningHub.Nhs.WebUI.AutomatedUiTests.csproj
- LearningHub.Nhs.WebUI/LearningHub.Nhs.WebUI.csproj
- OpenAPI/LearningHub.Nhs.OpenApi.Models/LearningHub.Nhs.OpenApi.Models.csproj
- OpenAPI/LearningHub.Nhs.OpenApi.Repositories.Interface/LearningHub.Nhs.OpenApi.Repositories.Interface.csproj
- OpenAPI/LearningHub.Nhs.OpenApi.Repositories/LearningHub.Nhs.OpenApi.Repositories.csproj
- OpenAPI/LearningHub.Nhs.OpenApi.Services.Interface/LearningHub.Nhs.OpenApi.Services.Interface.csproj
- OpenAPI/LearningHub.Nhs.OpenApi.Services/LearningHub.Nhs.OpenApi.Services.csproj
- OpenAPI/LearningHub.Nhs.OpenApi.Tests/LearningHub.Nhs.OpenApi.Tests.csproj
- OpenAPI/LearningHub.Nhs.OpenApi/LearningHub.NHS.OpenAPI.csproj
- ReportAPI/LearningHub.Nhs.ReportApi.Services.Interface/LearningHub.Nhs.ReportApi.Services.Interface.csproj
- ReportAPI/LearningHub.Nhs.ReportApi.Services.UnitTests/LearningHub.Nhs.ReportApi.Services.UnitTests.csproj
- ReportAPI/LearningHub.Nhs.ReportApi.Services/LearningHub.Nhs.ReportApi.Services.csproj
- ReportAPI/LearningHub.Nhs.ReportApi.Shared/LearningHub.Nhs.ReportApi.Shared.csproj
- ReportAPI/LearningHub.Nhs.ReportApi/LearningHub.Nhs.ReportApi.csproj
- WebAPI/LearningHub.Nhs.API/LearningHub.Nhs.Api.csproj
- WebAPI/LearningHub.Nhs.Api.Shared/LearningHub.Nhs.Api.Shared.csproj
- WebAPI/LearningHub.Nhs.Api.UnitTests/LearningHub.Nhs.Api.UnitTests.csproj
- WebAPI/LearningHub.Nhs.Repository.Interface/LearningHub.Nhs.Repository.Interface.csproj
- WebAPI/LearningHub.Nhs.Repository/LearningHub.Nhs.Repository.csproj
- WebAPI/LearningHub.Nhs.Services.Interface/LearningHub.Nhs.Services.Interface.csproj
- WebAPI/LearningHub.Nhs.Services.UnitTests/LearningHub.Nhs.Services.UnitTests.csproj
- WebAPI/LearningHub.Nhs.Services/LearningHub.Nhs.Services.csproj
- WebAPI/MigrationTool/LearningHub.Nhs.Migration.ConsoleApp/LearningHub.Nhs.Migration.ConsoleApp.csproj
- WebAPI/MigrationTool/LearningHub.Nhs.Migration.Interface/LearningHub.Nhs.Migration.Interface.csproj
- WebAPI/MigrationTool/LearningHub.Nhs.Migration.Models/LearningHub.Nhs.Migration.Models.csproj
- WebAPI/MigrationTool/LearningHub.Nhs.Migration.Staging.Repository/LearningHub.Nhs.Migration.Staging.Repository.csproj
- WebAPI/MigrationTool/LearningHub.Nhs.Migration.UnitTests/LearningHub.Nhs.Migration.UnitTests.csproj
- WebAPI/MigrationTool/LearningHub.Nhs.Migration/LearningHub.Nhs.Migration.csproj
> Merge Model version update to RC

- LearningHub.Nhs.WebUI/Styles/nhsuk/nhsuk-overrides.scss
- LearningHub.Nhs.WebUI/Views/Shared/Components/NavigationItems/MobileTopRightNav.cshtml
- LearningHub.Nhs.WebUI/Views/Shared/Components/NavigationItems/Topnav.cshtml
Associated Ticket : TD-5761 
Notification count re design 
-----
I have:
Either:
Or:
> Notification count design added
