- .gitguardian.yaml
- LearningHub.Nhs.WebUI/Controllers/Api/UserController.cs
- LearningHub.Nhs.WebUI/Controllers/ResourceController.cs
- LearningHub.Nhs.WebUI/Scripts/vuesrc/data/user.ts
- LearningHub.Nhs.WebUI/Scripts/vuesrc/resource/ResourceContent.vue
- LearningHub.Nhs.WebUI/Scripts/vuesrc/resource/blocks/ImageCarouselViewer.vue
- LearningHub.Nhs.WebUI/Services/SearchService.cs
- LearningHub.Nhs.WebUI/Views/Catalogue/Catalogues.cshtml
- LearningHub.Nhs.WebUI/Views/Home/_CatalogueCard.cshtml
- LearningHub.Nhs.WebUI/Views/Home/_ResourceCard.cshtml
- LearningHub.Nhs.WebUI/Views/Search/_CatalogueSearchResult.cshtml
- LearningHub.Nhs.WebUI/Views/Search/_ResourceSearchResult.cshtml
- WebAPI/LearningHub.Nhs.Database/Scripts/Post-Deploy/Scripts/ExternalSystemData.sql
- WebAPI/LearningHub.Nhs.Database/Stored Procedures/Hierarchy/GetNodeContentsForCatalogueBrowse.sql
- WebAPI/LearningHub.Nhs.Database/Stored Procedures/Hierarchy/GetNodeContentsForCatalogueBrowse_withEmptyFolders.sql
- WebAPI/LearningHub.Nhs.Services/HierarchyService.cs
> Rc hot fix

- .gitguardian.yaml
- .github/azure-pipeline-database-ci.yml
- .github/azure-pipeline-openapi-reportapi-ci.yml
- .github/azure-pipeline-webui-ci.yml
- .gitignore
- LearningHub.Nhs.WebUI/Controllers/Api/UserController.cs
- LearningHub.Nhs.WebUI/Controllers/ResourceController.cs
- LearningHub.Nhs.WebUI/Program.cs
- LearningHub.Nhs.WebUI/Scripts/vuesrc/data/user.ts
- LearningHub.Nhs.WebUI/Scripts/vuesrc/resource/ResourceContent.vue
- LearningHub.Nhs.WebUI/Scripts/vuesrc/resource/blocks/ImageCarouselViewer.vue
- LearningHub.Nhs.WebUI/Services/SearchService.cs
- LearningHub.Nhs.WebUI/Views/Catalogue/Catalogues.cshtml
- LearningHub.Nhs.WebUI/Views/Home/_CatalogueCard.cshtml
- LearningHub.Nhs.WebUI/Views/Home/_ResourceCard.cshtml
- LearningHub.Nhs.WebUI/Views/Search/_CatalogueSearchResult.cshtml
- LearningHub.Nhs.WebUI/Views/Search/_ResourceSearchResult.cshtml
- README.md
- WebAPI/LearningHub.Nhs.Database/Scripts/Post-Deploy/Scripts/ExternalSystemData.sql
- WebAPI/LearningHub.Nhs.Database/Stored Procedures/Hierarchy/GetNodeContentsForCatalogueBrowse.sql
- WebAPI/LearningHub.Nhs.Database/Stored Procedures/Hierarchy/GetNodeContentsForCatalogueBrowse_withEmptyFolders.sql
- WebAPI/LearningHub.Nhs.Services/HierarchyService.cs
> Bring RC changes to release/Phoenix

- LearningHub.Nhs.WebUI/Controllers/AccountController.cs
TD-3744
Job role with slash in causes error during registration.
-----
I have:
> TD-3744-Job role with slash in causes error during registration

- WebAPI/LearningHub.Nhs.Database/Stored Procedures/Resources/GetScormContentServerDetailsForHistoricExternalUrl.sql
https://hee-tis.atlassian.net/browse/TD-3839
Fixed the issue ESR Resources are not Loading and throwing 500 Errors.
-----
I have:
> TD-3839-Logs are Getting Saved in Production Log-Content Server Issues

- WebAPI/LearningHub.Nhs.Database/Stored Procedures/Resources/GetDashboardResources.sql
https://hee-tis.atlassian.net/browse/TD-3833
Fixed the performance issue with the resource tray loading.
-----
I have:
> TD-3833-Recently Added Tray Not Loading On Prod-Resources Tab

- LearningHub.Nhs.WebUI/Controllers/LearningSessionsController.cs
- WebAPI/LearningHub.Nhs.Services/ResourceService.cs
https://hee-tis.atlassian.net/browse/TD-3846
Logs are Getting Saved in Production Log-Resource Version - 
Implemented the fix to remove the null reference error from the API Call Resource/GetResourceItemViewModelAsync/{id}
-----
I have:
> TD-3846- Logs are Getting Saved in Production Log-Resource Version

- LearningHub.Nhs.WebUI/Scripts/vuesrc/models/learningsessions/cmiVocabulary.ts
- LearningHub.Nhs.WebUI/Scripts/vuesrc/models/learningsessions/scormApiModel.ts
https://hee-tis.atlassian.net/browse/TD-3823
Extended CmiSuspend_data limit from 4096 to 64000
Noticed few files are missing in Prod folder as below.
**_Before code fix:_**
**_After code fix._**
-----
I have:
> TD-3823: CmiSuspend_data limit extended from 4096 to 64000

- LearningHub.Nhs.WebUI/Scripts/vuesrc/resource/ResourceContent.vue
TD-3551 
Enable certificate link to be made available as soon as a video and audio resource are completed.
-----
I have:
> TD-3551 audio and video certificate visibility

- LearningHub.Nhs.WebUI/Controllers/ResourceController.cs
- LearningHub.Nhs.WebUI/Interfaces/IFileService.cs
- LearningHub.Nhs.WebUI/Services/FileService.cs
[TD-3881](https://hee-tis.atlassian.net/browse/TD-3881)
LH users are unable to seek a range from the entire playtime of a video content and clicking to navigate to any point in time in the video failed. Video and audio content within a html resource have now been configured to stream rather than download
not applicable
-----
I have:
[TD-3881]: https://hee-tis.atlassian.net/browse/TD-3881?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> TD-3881 stream audio or video file content within html resource

- LearningHub.Nhs.WebUI/Controllers/HomeController.cs
[TD-3950 ](https://hee-tis.atlassian.net/browse/TD-3950)
Adding resources to bookmarks returns an error when user has proceeded beyond page 1 of the dashboard trays
-----
I have:
> TD-3950 bookmark partial view error bugfix

- WebAPI/LearningHub.Nhs.Database/LearningHub.Nhs.Database.sqlproj
- WebAPI/LearningHub.Nhs.Database/Scripts/External/AddDigitalLearningSolutionsSso.sql
- WebAPI/LearningHub.Nhs.Database/Triggers/external/AddDigitalLearningSolutionsExternalSystem.sql
…ystem also includes DigitalLearningSolutionsSso external user system
_TD-###_
-----
I have:
> TD-3977-DLS users receiving "Your account cannot be validated" error when accessing LH through SSO

- LearningHub.Nhs.WebUI/Models/RestrictedAccessBannerViewModel.cs
- LearningHub.Nhs.WebUI/Views/Catalogue/Index.cshtml
- LearningHub.Nhs.WebUI/Views/Shared/_RestrictedAccessBanner.cshtml
TD-3699
If you remove a user from a restricted catalogue via the Manage Catalogue page, although they are removed from the usergroup, they still have access to the catalogue.
If however you remove a user via the usergroup directly, it does prevent their access.
-----
I have:
[TD-3699]: https://hee-tis.atlassian.net/browse/TD-3699?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Fixes-TD-3699

- LearningHub.Nhs.WebUI/Controllers/Api/ScormController.cs
- WebAPI/LearningHub.Nhs.Database/Stored Procedures/Activity/ScormActivityComplete.sql
https://hee-tis.atlassian.net/browse/TD-1325
https://hee-tis.atlassian.net/browse/TD-1325
**_Before code changes:_**
Disappeared after complete
Appeared again after window close
**_After code fix:_**
-----
I have:
> TD-1325: My Learning record disappearing after session completed

- LearningHub.Nhs.WebUI/Views/Resource/_ResourceItem.cshtml
[TD-3991](https://hee-tis.atlassian.net/browse/TD-3991)
some vue.js click event directive were missing
Not applicable
-----
I have:
[TD-3991]: https://hee-tis.atlassian.net/browse/TD-3991?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> TD-3991 Fix for certificate display for web and generic file resource

- LearningHub.Nhs.WebUI/Controllers/Api/ScormController.cs
https://hee-tis.atlassian.net/browse/TD-3955
eLearning with Passed type is also included when the user completes the learning and exit without proper closure
**_Before code change_**
-----
I have:
> TD-3955: eLearning with Passed type is also included when the user completes the learning and exit without proper closure

- LearningHub.Nhs.WebUI/Views/Resource/_ResourceItem.cshtml
TD-4014
HTML resource page displaying launch button twice
-----
I have:
- [] Written appropriate unit tests for the changes, including:
> TD-4014-HTML resource page displaying launch button twice

- LearningHub.Nhs.WebUI/Views/Home/Accessibility.cshtml
- LearningHub.Nhs.WebUI/Views/Home/NhsSites.cshtml
- LearningHub.Nhs.WebUI/Views/Policies/AcceptableUsePolicy.cshtml
- LearningHub.Nhs.WebUI/Views/Policies/ContentPolicy.cshtml
- LearningHub.Nhs.WebUI/Views/Policies/CookiePolicy.cshtml
- LearningHub.Nhs.WebUI/Views/Policies/PrivacyPolicy.cshtml
- LearningHub.Nhs.WebUI/Views/Policies/TermsConditions.cshtml
TD-3959
Update LH footer pages review dates
-----
I have:
> Fixes-TD-3959-Update  Review Date for all Pages

- WebAPI/LearningHub.Nhs.Repository/LearningHubDbContext.cs
- WebAPI/LearningHub.Nhs.Repository/Resources/BlockCollectionRepository.cs
[TD-3948](https://hee-tis.atlassian.net/browse/TD-3948)
The endpoint previously experienced timeouts when making repeated stored procedure calls to the database. To address this issue, the endpoint was modified to execute these calls without waiting for a confirmation response from the database. Consequently, a database context had to be manually instantiated and disposed within the loop to handle concurrency effectively.
Not available.
-----
I have:
[TD-3948]: https://hee-tis.atlassian.net/browse/TD-3948?atlOrigin=eyJpIjoiNWRkN …
> Auto Save button issue when updating case resources

- LearningHub.Nhs.WebUI/Views/Shared/_Breadcrumbs.cshtml
[_TD-###_](https://hee-tis.atlassian.net/browse/TD-3703)
Breadcrumb doesn't say where it links to - replace "parent" with with parent page title
-----
I have:
> TD-3703-Breadcrumb doesn't say where it links to - replace "parent" with with parent page title

- LearningHub.Nhs.WebUI/Scripts/vuesrc/mycontributions/gridcomponent.vue
[_TD-###_](https://hee-tis.atlassian.net/browse/TD-2959?atlOrigin=eyJpIjoiODZhM2Y3NzMwYmY2NDI1M2ExNDBjMjNhMzcyMjAxNjMiLCJwIjoiaiJ9)
Updated the edit resource message
Before:
After:
-----
I have:
> TD-4020 : incorrect message for edit resource my contributions

- LearningHub.Nhs.WebUI/Scripts/vuesrc/contribute-resource/SelectResourceType.vue
- LearningHub.Nhs.WebUI/Scripts/vuesrc/contribute/ContentVideo.vue
- LearningHub.Nhs.WebUI/Scripts/vuesrc/contribute/GenericFileUploader.vue
> TD-3285, vue cache storing the feature flag inconsistently, update the way its populating now

- LearningHub.Nhs.WebUI/Controllers/ResourceController.cs
TD-3023
limit the removal of output content to scorm and html resource during resource unpublish activity.
-----
I have:
> TD-3023 limit the removal of output content to scorm and html resource

- LearningHub.Nhs.WebUI/Controllers/Api/ScormController.cs
https://hee-tis.atlassian.net/browse/TD-3741
Implemented the logic to fix the issues related to the LMS server after releasing cache content on commit. 
-----
I have:
> TD-3741 - LMS server issue related to active content cache is null.

- LearningHub.Nhs.WebUI/Controllers/Api/ContributeController.cs
- LearningHub.Nhs.WebUI/Services/FileService.cs
- WebAPI/LearningHub.Nhs.Services/ResourceService.cs
[TD-4052](https://hee-tis.atlassian.net/browse/TD-4052)
this fix does a null check before checking the content of a list
-----
I have:
[TD-4052]: https://hee-tis.atlassian.net/browse/TD-4052?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> TD-4052 bugfix

- LearningHub.Nhs.WebUI/Scripts/vuesrc/contribute-resource/ContributeBlock.vue
- LearningHub.Nhs.WebUI/Scripts/vuesrc/contribute-resource/ContributeCaseOrAssessmentContent.vue
- LearningHub.Nhs.WebUI/Scripts/vuesrc/contribute-resource/components/content-tab/ChooseContentBlockOption.vue
- LearningHub.Nhs.WebUI/Scripts/vuesrc/contribute-resource/components/content-tab/ContributeMediaBlock.vue
- LearningHub.Nhs.WebUI/Scripts/vuesrc/contribute/Content.vue
- LearningHub.Nhs.WebUI/Scripts/vuesrc/helpers/fileUpload.ts
- LearningHub.Nhs.WebUI/Scripts/vuesrc/models/contribute-resource/blocks/mediaTypeEnum.ts
https://hee-tis.atlassian.net/browse/TD-3828)](https://hee-tis.atlassian.net/browse/TD-3828
-----
I have:
> AMS flag funcationality

- LearningHub.Nhs.WebUI/Controllers/Api/ContributeController.cs
- LearningHub.Nhs.WebUI/Services/FileService.cs
- WebAPI/LearningHub.Nhs.Services/ResourceService.cs
Added the removal of deleted case resource files to savecase and delete resource method.
-----
I have:
> TD-3023 move deleted case resource files to archive

- LearningHub.Nhs.WebUI/Styles/nhsuk/pages/bookmark.scss
- LearningHub.Nhs.WebUI/Styles/nhsuk/pages/catalogue.scss
- LearningHub.Nhs.WebUI/Views/Catalogue/_ContentStructure.cshtml
> Correct Skipped headiing issue for catalogue folders

- AdminUI/LearningHub.Nhs.AdminUI/Views/Catalogue/Edit.cshtml
https://hee-tis.atlassian.net/browse/TD-4057
Re-introduced the label with "Only the first 3,000 characters of the description will be used by search" message for description field.
Findwise data
-----
I have:
> TD-4057: Re-introduced the label with "Only the first 3,000 characters of the description will be used by search" message for description field.

- WebAPI/LearningHub.Nhs.Services/ResourceService.cs
TD-3023
Delete resource files associated with resources with only one version.
-----
I have:
> TD-3023 Delete files associated with resources without older versions

- WebAPI/LearningHub.Nhs.API/appsettings.json
- WebAPI/LearningHub.Nhs.Api.Shared/Configuration/FindwiseSettings.cs
- WebAPI/LearningHub.Nhs.Services/CatalogueService.cs
https://hee-tis.atlassian.net/browse/TD-4057
Description limit included in update and moved to appsettings file
-----
I have:
> TD-4057: Description limit moved to apsettings

- LearningHub.Nhs.WebUI/Services/FileService.cs
…rage.
TD-3023
Delete existing folder directory and subdirectory after migrating it alongside it's content to a backup storage.
-----
I have:
> TD-3023 Delete folder structure after copying folder content to backup storage

- LearningHub.Nhs.WebUI/Helpers/ViewActivityHelper.cs
- WebAPI/LearningHub.Nhs.Database/Stored Procedures/Activity/GetUserLatestActivityCheck.sql
- WebAPI/LearningHub.Nhs.Database/Stored Procedures/Activity/GetUserLearningActivities.sql
- WebAPI/LearningHub.Nhs.Database/Stored Procedures/Activity/GetUserLearningActivitiesCount.sql
https://hee-tis.atlassian.net/browse/TD-4106
Issue with Formal assessments learning record showing as '0%' for completed, passed & failed assessments and showing date incorrect
-----
I have:
> TD-4106: Issue with Formal assessments learning record showing as '0%' for completed, passed & failed assessments and showing date incorrect

- WebAPI/LearningHub.Nhs.Services/MyLearningService.cs
https://hee-tis.atlassian.net/browse/TD-4108
Issue1 :Certificate missing for Assessment-Informal when completed it.
Issue 2: Certificate missing for Assessment-Formal ones when completed/passed/failed
-----
I have:
> TD-4108: Fixed the issue with the certificate visibility

- WebAPI/LearningHub.Nhs.Database/Stored Procedures/Resources/GetDashboardResources.sql
https://hee-tis.atlassian.net/browse/TD-4115
Fixed the Issues on showing statuses on 'My accessed Learning' section of Learning Hub Home page
-----
I have:
> TD-4115 - Issues on showing statuses on 'My accessed Learning'

- LearningHub.Nhs.WebUI/Controllers/Api/ContributeController.cs
- WebAPI/LearningHub.Nhs.Services/ResourceService.cs
TD-3023
Fix for WSI images in a question block
Fix for deleted blocks which are valid in a published resource.
-----
I have:
> TD-3023 fix for deleted blocks which are valid in an active  resource version

- LearningHub.Nhs.WebUI/Helpers/ViewActivityHelper.cs
https://hee-tis.atlassian.net/browse/TD-3740?atlOrigin=eyJpIjoiZWIzYmJkOWYyYWE5NGRmM2EyMjFmZDViOThlODZkZTciLCJwIjoiaiJ9
added latest version check in View progress link condition
-----
I have:
> TD-3740 video progress link displayed for old resource versions

- LearningHub.Nhs.WebUI/Controllers/Api/ContributeController.cs
- WebAPI/LearningHub.Nhs.Services/ResourceService.cs
added null check for wsi in question block.
added an inverse blockcollection file search when publishing new case resource version.
-----
I have:
> TD-3023 QuestionBlock wsi and draft published case file  bugfix 

- WebAPI/LearningHub.Nhs.Database/Stored Procedures/Resources/GetDashboardResources.sql
https://hee-tis.atlassian.net/browse/TD-4115
Issues on showing statuses on 'My accessed Learning' section of Learning Hub Home page
-----
I have:
> TD-4115: Issues on showing statuses on 'My accessed Learning' sectionof Learning Hub Home page

- LearningHub.Nhs.WebUI/Controllers/Api/ContributeController.cs
- WebAPI/LearningHub.Nhs.Services/ResourceService.cs
TD-3023
exclude wsi that are still processing.  when purging case files
-----
I have:
> TD-3023 exclude wsi that are still processing.

- LearningHub.Nhs.WebUI/Controllers/Api/ContributeController.cs
- WebAPI/LearningHub.Nhs.Database/Stored Procedures/Resources/AssessmentContentBlockCollectionGetAll.sql
- WebAPI/LearningHub.Nhs.Database/Stored Procedures/Resources/AssessmentGuidanceBlockCollectionGetAll.sql
- WebAPI/LearningHub.Nhs.Database/Stored Procedures/Resources/CaseBlockCollectionGetAll.sql
- WebAPI/LearningHub.Nhs.Repository.Interface/Resources/IBlockCollectionRepository.cs
- WebAPI/LearningHub.Nhs.Repository/Resources/BlockCollectionRepository.cs
- WebAPI/LearningHub.Nhs.Services.Interface/IResourceService.cs
- WebAPI/LearningHub.Nhs.Services/ResourceService.cs
When archiving we need to ensure that files are only archived if there are no longer any references to them, by any resource including copies(cases and assessment)
-----
I have:
> TD-3023 Update to search entire db for case and assessment blocks

- WebAPI/LearningHub.Nhs.Database/Stored Procedures/Hub/RestrictedCatalogueGetAccessRequests.sql
https://hee-tis.atlassian.net/browse/TD-4203
Considering only active users IN Catalogue access request
**_Before code change:_**
-----
I have:
> TD-4023: Considering only active users IN Catalogue access request

- LearningHub.Nhs.WebUI/Controllers/Api/ContributeController.cs
- WebAPI/LearningHub.Nhs.Services/ResourceService.cs
> TD-3023 wsi archiving after processing fix

- LearningHub.Nhs.WebUI/Controllers/Api/ContributeController.cs
- WebAPI/LearningHub.Nhs.Services/ResourceService.cs
TD-3023
WSI in the question block automatically archives when processing completes, and this is due to the fact that the wholesideimages are lost upon completion. The file-Id is however retained and this is now used in scanning for deleted files instead 
of the path.
-----
I have:
> TD-3023 wsi auto archiving fix

- WebAPI/LearningHub.Nhs.API/Controllers/ResourceController.cs
- WebAPI/LearningHub.Nhs.Repository.Interface/Resources/IResourceVersionRepository.cs
- WebAPI/LearningHub.Nhs.Repository/Resources/ResourceVersionRepository.cs
- WebAPI/LearningHub.Nhs.Services.Interface/IResourceService.cs
- WebAPI/LearningHub.Nhs.Services/ResourceService.cs
https://hee-tis.atlassian.net/browse/TD-4234
Modified GetExternalContentDetailsById (Web API) API call and change it to async Call
**_Before and after the code changes, the Resource details page is working as expected._**
-----
I have:
> TD-4234: Modified GetExternalContentDetailsById (Web API) API call and change it to async Call

- AdminUI/LearningHub.Nhs.AdminUI/Scripts/vuesrc/content/cmsPageRow.vue
- AdminUI/LearningHub.Nhs.AdminUI/Services/MKIOMediaService.cs
- LearningHub.Nhs.WebUI/Scripts/vuesrc/contribute-resource/components/MKIOVideoPlayer.vue
- LearningHub.Nhs.WebUI/Scripts/vuesrc/resource/ResourceContent.vue
- LearningHub.Nhs.WebUI/Services/MKIOMediaService.cs
> Fixed the error while launching the scorm content and javascript error

- WebAPI/LearningHub.Nhs.API/Controllers/ContentServerController.cs
- WebAPI/LearningHub.Nhs.Repository.Interface/Resources/IScormResourceVersionRepository.cs
- WebAPI/LearningHub.Nhs.Repository/Resources/ScormResourceVersionRepository.cs
- WebAPI/LearningHub.Nhs.Services.Interface/IScormContentServerService.cs
- WebAPI/LearningHub.Nhs.Services/ScormContentServerService.cs
https://hee-tis.atlassian.net/browse/TD-4151
Converted below API call into an async
1. GetContentDetailsByExternalUrl
2. GetContentDetailsByExternalReference
-----
I have:
> TD-4151 - Converted API call in to async

- AdminUI/LearningHub.Nhs.AdminUI/Scripts/vuesrc/content/upload/fileValidation.ts
- LearningHub.Nhs.WebUI/Scripts/vuesrc/resource/ResourceContent.vue
- WebAPI/LearningHub.Nhs.API/Controllers/ContentServerController.cs
- WebAPI/LearningHub.Nhs.API/Controllers/ResourceController.cs
- WebAPI/LearningHub.Nhs.Database/Scripts/Post-Deploy/Scripts/TD-4031_AMStoMKIOMigration.sql
- WebAPI/LearningHub.Nhs.Repository.Interface/Resources/IResourceVersionRepository.cs
- WebAPI/LearningHub.Nhs.Repository.Interface/Resources/IScormResourceVersionRepository.cs
- WebAPI/LearningHub.Nhs.Repository/Resources/ResourceVersionRepository.cs
- WebAPI/LearningHub.Nhs.Repository/Resources/ScormResourceVersionRepository.cs
- WebAPI/LearningHub.Nhs.Services.Interface/IResourceService.cs
- WebAPI/LearningHub.Nhs.Services.Interface/IScormContentServerService.cs
- WebAPI/LearningHub.Nhs.Services/ResourceService.cs
- WebAPI/LearningHub.Nhs.Services/ScormContentServerService.cs
> Fixing video tracking and Admin UI file validation

- LearningHub.Nhs.WebUI/Controllers/Api/ResourceController.cs
- LearningHub.Nhs.WebUI/Scripts/vuesrc/contribute/Content.vue
- LearningHub.Nhs.WebUI/Scripts/vuesrc/data/resource.ts
- WebAPI/LearningHub.Nhs.Services/ResourceService.cs
[TD-4226](https://hee-tis.atlassian.net/browse/TD-4226)
Fix for files associated with draft resources
-----
I have:
[TD-4226]: https://hee-tis.atlassian.net/browse/TD-4226?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> TD-4226 AMS storage additional bugs

- LearningHub.Nhs.WebUI/Controllers/CatalogueController.cs
- LearningHub.Nhs.WebUI/Controllers/ResourceController.cs
- LearningHub.Nhs.WebUI/Services/ResourceService.cs
- WebAPI/LearningHub.Nhs.API/Controllers/HierarchyController.cs
- WebAPI/LearningHub.Nhs.API/Controllers/UserGroupController.cs
- WebAPI/LearningHub.Nhs.Database/Stored Procedures/Hierarchy/GetNodeContentsForCatalogueBrowse.sql
- WebAPI/LearningHub.Nhs.Database/Stored Procedures/Hub/RoleUserGroupGetByUserGroupId.sql
- WebAPI/LearningHub.Nhs.Database/Stored Procedures/Hub/RoleUserGroupGetByUserId.sql
- WebAPI/LearningHub.Nhs.Database/Stored Procedures/Resources/GetDashboardResources.sql
- WebAPI/LearningHub.Nhs.Database/Views/RoleUserGroupView.sql
- WebAPI/LearningHub.Nhs.Repository.Interface/Hierarchy/INodeRepository.cs
- WebAPI/LearningHub.Nhs.Repository.Interface/IRoleUserGroupRepository.cs
- WebAPI/LearningHub.Nhs.Repository/Hierarchy/NodeRepository.cs
- WebAPI/LearningHub.Nhs.Repository/LearningHubDbContext.cs
- WebAPI/LearningHub.Nhs.Repository/Resources/ResourceVersionRatingRepository.cs
- WebAPI/LearningHub.Nhs.Repository/RoleUserGroupRepository.cs
- WebAPI/LearningHub.Nhs.Services.Interface/IHierarchyService.cs
- WebAPI/LearningHub.Nhs.Services.Interface/IUserGroupService.cs
- WebAPI/LearningHub.Nhs.Services/CatalogueService.cs
- WebAPI/LearningHub.Nhs.Services/HierarchyService.cs
- WebAPI/LearningHub.Nhs.Services/LearningHub.Nhs.Services.csproj
- WebAPI/LearningHub.Nhs.Services/MigrationService.cs
- WebAPI/LearningHub.Nhs.Services/RatingService.cs
- WebAPI/LearningHub.Nhs.Services/ResourceService.cs
- WebAPI/LearningHub.Nhs.Services/UserGroupService.cs
https://hee-tis.atlassian.net/browse/TD-4212
https://hee-tis.atlassian.net/browse/TD-4231
https://hee-tis.atlassian.net/browse/TD-4257
Analysed and fixed some of the errors from production log table
1. SQL timeout exceptions
2. Sql null exceptions
3. Object reference exceptions
-----
I have:
> TD-4212, TD-4231, TD-4257 - Error log issues

- LearningHub.Nhs.WebUI/Services/UserGroupService.cs
TD-4273
cache RoleUserGroupDetailForUser data
-----
I have:
> Cache hub.RoleUserGroupGetByUserId in webui

- LearningHub.Nhs.WebUI/Views/Search/_ResourceSearchResult.cshtml
https://hee-tis.atlassian.net/browse/TD-4330
fixed the issues with the resource links in search results direct to error page.
-----
I have:
> TD-4330: Resource links in search results direct to error page

- AdminUI/LearningHub.Nhs.AdminUI/Views/User/_UserLearningRecord.cshtml
_TD-3694
After updating a resource, last accessed date not displayed on admin user learning record
-----
I have:
> TD-3694-After updating a resource, last accessed date not displayed on admin user learning record

- WebAPI/LearningHub.Nhs.Database/LearningHub.Nhs.Database.sqlproj
TD-4211
This script will now have to be manually executed against the db
-----
I have:
> disable script build for TD-4211

- LearningHub.Nhs.WebUI/Scripts/vuesrc/contribute/ContentCommon.vue
https://hee-tis.atlassian.net/browse/TD-3308
Implemented additional validation message , if the user enter a keywords with more than 50 characters. 
-----
I have:
> TD-3308 : Added additional error message on the contribute screen

- LearningHub.Nhs.WebUI/Controllers/Api/ResourceController.cs
- LearningHub.Nhs.WebUI/Views/Resource/Resource.cshtml
_[TD-4421](https://hee-tis.atlassian.net/browse/TD-4421)_
Fixed issue on recording resource activity for resource type 'Files' when downloaded. Also, redirected the method for downloading elearning resources.
-----
I have:
[TD-4421]: https://hee-tis.atlassian.net/browse/TD-4421?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> TD-4421 : Fixed issue on recording resource activity for resource type 'Files' when downloaded.

- LearningHub.Nhs.WebUI/Scripts/vuesrc/resource/blocks/BlocksView.vue
- LearningHub.Nhs.WebUI/Scripts/vuesrc/resource/blocks/QuestionBlock.vue
_[TD-3707](https://hee-tis.atlassian.net/browse/TD-3707)_
In Assessments fixed issue on first question expanding after all questions answered.
After
-----
I have:
[TD-3707]: https://hee-tis.atlassian.net/browse/TD-3707?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> TD-3707: In Assessments - fixed issue on first question expanding after all questions answered.

- AdminUI/LearningHub.Nhs.AdminUI/LearningHub.Nhs.AdminUI.csproj
- LearningHub.Nhs.WebUI/LearningHub.Nhs.WebUI.csproj
- WebAPI/LearningHub.Nhs.API/LearningHub.Nhs.Api.csproj
- WebAPI/LearningHub.Nhs.Api.Shared/LearningHub.Nhs.Api.Shared.csproj
- WebAPI/LearningHub.Nhs.Api.UnitTests/LearningHub.Nhs.Api.UnitTests.csproj
- WebAPI/LearningHub.Nhs.Repository.Interface/LearningHub.Nhs.Repository.Interface.csproj
- WebAPI/LearningHub.Nhs.Repository/LearningHub.Nhs.Repository.csproj
- WebAPI/LearningHub.Nhs.Services.Interface/LearningHub.Nhs.Services.Interface.csproj
- WebAPI/LearningHub.Nhs.Services.UnitTests/LearningHub.Nhs.Services.UnitTests.csproj
- WebAPI/LearningHub.Nhs.Services/LearningHub.Nhs.Services.csproj
- WebAPI/MigrationTool/LearningHub.Nhs.Migration.ConsoleApp/LearningHub.Nhs.Migration.ConsoleApp.csproj
- WebAPI/MigrationTool/LearningHub.Nhs.Migration.Interface/LearningHub.Nhs.Migration.Interface.csproj
- WebAPI/MigrationTool/LearningHub.Nhs.Migration.Models/LearningHub.Nhs.Migration.Models.csproj
- WebAPI/MigrationTool/LearningHub.Nhs.Migration.Staging.Repository/LearningHub.Nhs.Migration.Staging.Repository.csproj
- WebAPI/MigrationTool/LearningHub.Nhs.Migration.UnitTests/LearningHub.Nhs.Migration.UnitTests.csproj
- WebAPI/MigrationTool/LearningHub.Nhs.Migration/LearningHub.Nhs.Migration.csproj
[TD-4417](https://hee-tis.atlassian.net/browse/TD-4417)
LH model update. There was a character count validation on textbox blocks which upon failure, made resource publish to fail. This validation has now been removed and user can allowed to input as much text as needed. The code change was in the LH nuget package.
-----
I have:
[TD-4417]: https://hee-tis.atlassian.net/browse/TD-4417?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> learningHub model version update

- WebAPI/LearningHub.Nhs.Repository/Hierarchy/CatalogueNodeVersionRepository.cs
Implemented a conditional check to address scenarios where the initial query to fetch catalogues yields an empty list. In such cases, a secondary, more targeted query is executed. This alternative query returns the original catalogue based on `NodePathId` to ensure at least one catalogue is returned.
TD-4401
I have:
> TD-4401 Add fallback query for empty catalogues

- AdminUI/LearningHub.Nhs.AdminUI/Helpers/LearningActivityHelper.cs
- LearningHub.Nhs.WebUI/Helpers/ViewActivityHelper.cs
TD-3694
_After updating a resource, last accessed date not displayed on admin user learning record_
-----
I have:
> TD-3694-Fixes-For-HTML and  Case  Resource

- WebAPI/LearningHub.Nhs.Database/Stored Procedures/Activity/GetUserLearningActivities.sql
- WebAPI/LearningHub.Nhs.Database/Stored Procedures/Activity/GetUserLearningActivitiesCount.sql
_[TD-4411](https://hee-tis.atlassian.net/browse/TD-4411)_
Fixed the issue related to the result getting for 'Completed' filter along with 'Assessment' filter in MyLearning page.
After:
-----
I have:
[TD-4411]: https://hee-tis.atlassian.net/browse/TD-4411?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> TD-4411: Fixed filter result for 'Completed' filter along with 'Assessment'.

- LearningHub.Nhs.WebUI/Scripts/vuesrc/contribute-resource/ContributeAssessmentSettings.vue
[_TD-###_](https://hee-tis.atlassian.net/browse/TD-4388)
Assessment resource settings need a required field marker
-----
I have:
> TD-4388-Assessment resource settings need a required field marker

- AdminUI/LearningHub.Nhs.AdminUI/Views/Catalogue/Edit.cshtml
- LearningHub.Nhs.WebUI/Scripts/vuesrc/contribute-resource/components/KeyWordsEditor.vue
- LearningHub.Nhs.WebUI/Scripts/vuesrc/contribute/ContentCommon.vue
- WebAPI/LearningHub.Nhs.Services/ResourceService.cs
_[TD-4430](https://hee-tis.atlassian.net/browse/TD-4430)_
Fixed duplicate keywords issue in WebUI including case and assessment page and AdminUI.
After
-----
I have:
[TD-4430]: https://hee-tis.atlassian.net/browse/TD-4430?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> TD-4430 : Issue when adding duplicate keywords on 'Keywords' section when contributing resources and on Admin section

- .gitignore
- OpenAPI/LearningHub.Nhs.OpenApi.Models/LearningHub.Nhs.OpenApi.Models.csproj
- OpenAPI/LearningHub.Nhs.OpenApi.Models/ViewModels/ResourceMetadataViewModel.cs
- OpenAPI/LearningHub.Nhs.OpenApi.Models/ViewModels/ResourceReferenceWithResourceDetailsViewModel.cs
- OpenAPI/LearningHub.Nhs.OpenApi.Repositories.Interface/Repositories/IResourceRepository.cs
- OpenAPI/LearningHub.Nhs.OpenApi.Repositories/EntityFramework/LearningHubDbContext.cs
- OpenAPI/LearningHub.Nhs.OpenApi.Repositories/EntityFramework/ServiceMappings.cs
- OpenAPI/LearningHub.Nhs.OpenApi.Repositories/Map/Content/PageSectionDetailMap.cs
- OpenAPI/LearningHub.Nhs.OpenApi.Repositories/Map/LogMap.cs
- OpenAPI/LearningHub.Nhs.OpenApi.Repositories/Map/Resources/Blocks/WholeSlideImageAnnotationMap.cs
- OpenAPI/LearningHub.Nhs.OpenApi.Repositories/Map/Resources/Blocks/WholeSlideImageAnnotationMarkMap.cs
- OpenAPI/LearningHub.Nhs.OpenApi.Repositories/Map/Resources/ResourceVersionMap.cs
- OpenAPI/LearningHub.Nhs.OpenApi.Repositories/Repositories/ResourceRepository.cs
- OpenAPI/LearningHub.Nhs.OpenApi.Services.Interface/LearningHub.Nhs.OpenApi.Services.Interface.csproj
- OpenAPI/LearningHub.Nhs.OpenApi.Services.Interface/Services/IResourceService.cs
- OpenAPI/LearningHub.Nhs.OpenApi.Services.Interface/Services/ISearchService.cs
- OpenAPI/LearningHub.Nhs.OpenApi.Services/LearningHub.Nhs.OpenApi.Services.csproj
- OpenAPI/LearningHub.Nhs.OpenApi.Services/Services/ResourceService.cs
- OpenAPI/LearningHub.Nhs.OpenApi.Services/Services/SearchService.cs
- OpenAPI/LearningHub.Nhs.OpenApi.Tests/Controllers/ResourceControllerTests.cs
- OpenAPI/LearningHub.Nhs.OpenApi.Tests/Services/Services/ResourceServiceTests.cs
- OpenAPI/LearningHub.Nhs.OpenApi.Tests/Services/Services/SearchServiceTests.cs
- OpenAPI/LearningHub.Nhs.OpenApi/Controllers/OpenApiControllerBase.cs
- OpenAPI/LearningHub.Nhs.OpenApi/Controllers/ResourceController.cs
- OpenAPI/LearningHub.Nhs.OpenApi/LearningHub.NHS.OpenAPI.csproj.user
- WebAPI/LearningHub.Nhs.Database/LearningHub.Nhs.Database.sqlproj
- WebAPI/LearningHub.Nhs.Database/Stored Procedures/Activity/GetResourceActivityPerResourceMajorVersion.sql
> Merge Openapi Changes-NHS staff app

- AdminUI/LearningHub.Nhs.AdminUI/Scripts/vuesrc/content-structure/treeItem.vue
- LearningHub.Nhs.WebUI/Scripts/vuesrc/content-structure-admin/treeItem.vue
[TD-4402](https://hee-tis.atlassian.net/browse/TD-4402)
Added `resourceNotInFolder` to prevent duplicate resources in folders and updated conditions for "Move here" and "Create reference here" links. Introduced `canShowHeaderOptions` to control header options visibility based on edit mode and item depth. Replaced `isMovingResource` with `isMovingOrReferencingResource` for better state handling. Added CSS rules for minimum height of `.treeview-node-inner`. Included missing properties in the initial state and ensured proper loading and checking of node contents.
-----
I have: …
> TD-4402 - Prevent duplicate resources in folders

- .gitignore
- OpenAPI/LearningHub.Nhs.OpenApi/Controllers/BookmarkController.cs
- OpenAPI/LearningHub.Nhs.OpenApi/Controllers/OpenApiControllerBase.cs
- OpenAPI/LearningHub.Nhs.OpenApi/SwaggerDefinitions/v1.3.0.json
_TD-3678
Minor change to swagger version
-----
I have:
- [ x] Run the formatter and made sure there are no IDE errors
- [ x] Written appropriate unit tests for the changes, including:
- [ x] Manually tested my work with and without JavaScript
- [ x] Tested any Views or partials created or changed with [Wave Chrome plugin](https://chrome.google.com/webstore/detail/wave-evaluation-tool/jbbplnpkjmmeebjpijfedlgcdilocofh/related) and addressed any valid accessibility issues
- [ x] Updated/added documentation in [Confluence](https://hee-tis.atlassian.net/wiki/spaces/TP/pages/3477930003/Learning+Hub) and/or …
> Swagger file was missing certificates endpoint

- AdminUI/LearningHub.Nhs.AdminUI/Views/User/_UserLearningRecord.cshtml
TD-3694
Prior to any fixes, the Admin user learning record page removed the hyperlink for old versions of resources, as per the my learning page. 
Now a fix has been applied, there is a hyperlink for all admin user learning records, even if the resource has been updated. If you select the hyperlink on a record of a resource that has since been updated, it takes you to the latest version (which can be seen on Seema’s video).
Suggest removing hyperlinks on updated resources as per the my learning page. 
-----
I have:
> TD-3694-defect fix for URL  Issue

- LearningHub.Nhs.WebUI/Controllers/Api/ContributeController.cs
- WebAPI/LearningHub.Nhs.Database/Stored Procedures/Hierarchy/CatalogueCreate.sql
- WebAPI/LearningHub.Nhs.Repository/Resources/ResourceVersionRepository.cs
https://hee-tis.atlassian.net/browse/TD-4570
Options are not getting populated in Hierarchy Edit Screen -For Newly created resources or folders from Contribute screen.
-----
I have:
> Td 4570 options are not poulating in the hierachy edit screen

- LearningHub.Nhs.WebUI/Controllers/LearningSessionsController.cs
_[TD-4283](https://hee-tis.atlassian.net/browse/TD-4283)_
_Removed the Referer URL checking when loading scorm contents._
-----
I have:
[TD-4283]: https://hee-tis.atlassian.net/browse/TD-4283?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> TD-4283: Fixed download issue for elearning resource in firefox browser

- LearningHub.Nhs.WebUI/Controllers/Api/HierarchyController.cs
- LearningHub.Nhs.WebUI/Interfaces/IHierarchyService.cs
- LearningHub.Nhs.WebUI/Scripts/vuesrc/content-structure-editor/contentStructureState.ts
- LearningHub.Nhs.WebUI/Scripts/vuesrc/content-structure-editor/treeItem.vue
- LearningHub.Nhs.WebUI/Scripts/vuesrc/data/contentStructure.ts
- LearningHub.Nhs.WebUI/Services/HierarchyService.cs
- WebAPI/LearningHub.Nhs.API/Controllers/HierarchyController.cs
- WebAPI/LearningHub.Nhs.Database/LearningHub.Nhs.Database.sqlproj
- WebAPI/LearningHub.Nhs.Database/Stored Procedures/Hierarchy/CheckCatalogueHasExternalReference.sql
- WebAPI/LearningHub.Nhs.Repository.Interface/Hierarchy/INodeRepository.cs
- WebAPI/LearningHub.Nhs.Repository/Hierarchy/NodeRepository.cs
- WebAPI/LearningHub.Nhs.Services.Interface/IHierarchyService.cs
- WebAPI/LearningHub.Nhs.Services/HierarchyService.cs
https://hee-tis.atlassian.net/browse/TD-4336
Remove "Move" functionality from externally referenced catalogues
**_Primary catalogue:_**
**_Catalogue under which externally referenced._**
-----
I have:
> TD-4336: Implement Code Changes in Web UI-My contributions Page

- WebAPI/LearningHub.Nhs.Database/LearningHub.Nhs.Database.sqlproj
- WebAPI/LearningHub.Nhs.Database/Stored Procedures/Hierarchy/HierarchyEditPublish.sql
- WebAPI/LearningHub.Nhs.Database/Stored Procedures/Hierarchy/HierarchyNewNodePathForReferedCatalogue.sql
https://hee-tis.atlassian.net/browse/TD-4394
Publishing catalogues needs to update referencing catalogues
**_Scenarios checked:_**
1. Created 2 Catalogues Ext1 and Ext2
2. Created a new folder under Ext2
3. Added external reference of 10-Level1 (Ext1) to Ext2
4.  After publish created new folder 11-Level2 under 10-Level1
5. Renamed child folder 11-Level2 to Level2Rename which reflected under Ext1 too. 
6. Added again new folder under 10-Level1 (Ext2) which reflects under Ext1 too.
7. Moved up folders which also reflected in Ext1
8.  Contributed a new Resource to Ext2 > 10- Level1 which reflected in Ext1 > 100 -Level1 > 10 -Level1
-----
I have:
- …
> TD-4394: Publishing catalogues needs to update referencing catalogues

- LearningHub.Nhs.WebUI/Controllers/CatalogueController.cs
- LearningHub.Nhs.WebUI/Views/Catalogue/AllCatalogueSearch.cshtml
_[TD-4038](https://hee-tis.atlassian.net/browse/TD-4038)_
Fixed pagination and lower case search term converting issue in All Catalogue page.
After
-----
I have:
[TD-4038]: https://hee-tis.atlassian.net/browse/TD-4038?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> TD-4038: Fixed AllCatalogue pagination issue

- LearningHub.Nhs.WebUI/Controllers/ResourceController.cs
TD-4299
time limit that  SET(10 seconds, say) before which another launch is not recorded for image and article resource
-----
I have:
> TD-4299-User Activity for Image/article resource  recorded after a delay 

- WebAPI/LearningHub.Nhs.API/Controllers/SearchController.cs
- WebAPI/LearningHub.Nhs.Repository.Interface/IRoleUserGroupRepository.cs
- WebAPI/LearningHub.Nhs.Repository/RoleUserGroupRepository.cs
- WebAPI/LearningHub.Nhs.Services.Interface/ICatalogueService.cs
- WebAPI/LearningHub.Nhs.Services/CatalogueService.cs
_[TD-4703](https://hee-tis.atlassian.net/browse/TD-4703)_
Fixed the issue showing unknown error occurring during pagination in allcatalogue and main search pages.
-----
I have:
[TD-4703]: https://hee-tis.atlassian.net/browse/TD-4703?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> TD-4703: Fixed issue showing 'unknown error' on 'search' and 'all catalogue search' results screens when navigated to the paginated next pages

- LearningHub.Nhs.WebUI/Views/Catalogue/AllCatalogueSearch.cshtml
- LearningHub.Nhs.WebUI/Views/Search/Index.cshtml
_[TD-4038](https://hee-tis.atlassian.net/browse/TD-4038)_
Message updated when doing an empty search in AllCatalogues and main search pages.
After
-----
I have:
[TD-4038]: https://hee-tis.atlassian.net/browse/TD-4038?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> TD-4038: Message updated for empty search in AllCatalogues and main search pages

- AdminUI/LearningHub.Nhs.AdminUI/Scripts/vuesrc/content-structure/treeItem.vue
- LearningHub.Nhs.WebUI/Scripts/vuesrc/content-structure-admin/treeItem.vue
- WebAPI/LearningHub.Nhs.Database/LearningHub.Nhs.Database.sqlproj
- WebAPI/LearningHub.Nhs.Database/Stored Procedures/Hierarchy/HierarchyEditPublish.sql
- WebAPI/LearningHub.Nhs.Database/Stored Procedures/Hierarchy/HierarchyNewResourceReferenceForReferedCatalogue.sql
https://hee-tis.atlassian.net/browse/TD-4650
Remove this reference" option should not be available in Primary catalogue after adding external reference
-----
I have:
> TD-4650: Remove this reference" option should not be available in Primary catalogue after adding external reference

- LearningHub.Nhs.WebUI/Views/Policies/PrivacyPolicy.cshtml
TD-4651
_when clicked below  link on the footer pages seeing console ‘404’ error on the screen .  Modified  with correct link
-----
I have:
> TD-4651-fix for Showing page '404' error for few links showing on footer pages

- OpenAPI/LearningHub.Nhs.OpenApi/Controllers/ResourceController.cs
> LH Virgo Changes-Related to Open API

- WebAPI/LearningHub.Nhs.Database/Stored Procedures/Hierarchy/NodeResourcePublish.sql
https://hee-tis.atlassian.net/browse/TD-4736
Resource which is contributed after external referencing is not showing under the folder of primary catalogue in edit mode
**_Resource contributed before external reference_**
**_Externally refetrenced under Sec2_**
Resource contributed after  adding externally reference
**_In edit mode_**
-----
I have:
> TD-4736: Resource which is contributed after external referencing is not showing under the folder of primary catalogue in edit mode

- AdminUI/LearningHub.Nhs.AdminUI/LearningHub.Nhs.AdminUI.csproj
- LearningHub.Nhs.WebUI/Controllers/CatalogueController.cs
- LearningHub.Nhs.WebUI/Controllers/SearchController.cs
- LearningHub.Nhs.WebUI/LearningHub.Nhs.WebUI.csproj
- LearningHub.Nhs.WebUI/Views/Catalogue/Catalogues.cshtml
- LearningHub.Nhs.WebUI/Views/Search/_CatalogueSearchResult.cshtml
- LearningHub.Nhs.WebUI/Views/Search/_ResourceSearchResult.cshtml
- WebAPI/LearningHub.Nhs.API/LearningHub.Nhs.Api.csproj
- WebAPI/LearningHub.Nhs.Api.Shared/LearningHub.Nhs.Api.Shared.csproj
- WebAPI/LearningHub.Nhs.Api.UnitTests/LearningHub.Nhs.Api.UnitTests.csproj
- WebAPI/LearningHub.Nhs.Repository.Interface/LearningHub.Nhs.Repository.Interface.csproj
- WebAPI/LearningHub.Nhs.Repository/LearningHub.Nhs.Repository.csproj
- WebAPI/LearningHub.Nhs.Services.Interface/LearningHub.Nhs.Services.Interface.csproj
- WebAPI/LearningHub.Nhs.Services.UnitTests/LearningHub.Nhs.Services.UnitTests.csproj
- WebAPI/LearningHub.Nhs.Services/LearningHub.Nhs.Services.csproj
- WebAPI/LearningHub.Nhs.Services/SearchService.cs
- WebAPI/MigrationTool/LearningHub.Nhs.Migration.ConsoleApp/LearningHub.Nhs.Migration.ConsoleApp.csproj
- WebAPI/MigrationTool/LearningHub.Nhs.Migration.Interface/LearningHub.Nhs.Migration.Interface.csproj
- WebAPI/MigrationTool/LearningHub.Nhs.Migration.Models/LearningHub.Nhs.Migration.Models.csproj
- WebAPI/MigrationTool/LearningHub.Nhs.Migration.Staging.Repository/LearningHub.Nhs.Migration.Staging.Repository.csproj
- WebAPI/MigrationTool/LearningHub.Nhs.Migration.UnitTests/LearningHub.Nhs.Migration.UnitTests.csproj
- WebAPI/MigrationTool/LearningHub.Nhs.Migration/LearningHub.Nhs.Migration.csproj
_[TD-4682](https://hee-tis.atlassian.net/browse/TD-4682)_
Fixed click logs issue in click data send to find wise.
-----
I have:
[TD-4682]: https://hee-tis.atlassian.net/browse/TD-4682?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> TD-4682: fix click logs issue -Find-wise

- LearningHub.Nhs.WebUI/Views/LearningSessions/Scorm.cshtml
> Add title attribute to iframe element

- WebAPI/LearningHub.Nhs.Database/LearningHub.Nhs.Database.sqlproj
- WebAPI/LearningHub.Nhs.Database/Scripts/Post-Deploy/Scripts/PPSXFileType.sql
https://hee-tis.atlassian.net/browse/TD-4373
Allowed .ppsx file types on the learning hub
-----
I have:
- Allowed File Types([Allowed File Types](https://hee-tis.atlassian.net/wiki/spaces/TP/pages/3960406046/File+Upload+-+Table+Identifying+What+File+Types+We+LH+Supports))
> TD-4373-Allow .ppsx file types

- AdminUI/LearningHub.Nhs.AdminUI/Scripts/vuesrc/content-structure/contentStructureState.ts
https://hee-tis.atlassian.net/browse/TD-4408
Creating a reference/folder to a resource does not refresh all instances of the resource
https://github.com/user-attachments/assets/e1c5bb45-28af-4046-b9c8-a7cbd71c3bb1
-----
I have:
> TD-4408: Creating a reference/folder to a resource does not refresh all instances of the resource

- LearningHub.Nhs.WebUI/Scripts/vuesrc/content-structure-admin/contentStructureState.ts
https://hee-tis.atlassian.net/browse/TD-4408
Creating a reference/folder to a resource does not refresh all instances of the resource
-----
I have:
> TD-4408: Added code changes in WebUI too

- LearningHub.Nhs.WebUI/Scripts/vuesrc/contribute-resource/ContributeAssessmentSettings.vue
https://hee-tis.atlassian.net/browse/TD-4388
Assessment resource settings need a required field marker - Fixed the SIT defects
**Without description**
**With Description**
-----
I have:
> TD-4388: Assessment resource settings need a required field marker

- OpenAPI/LearningHub.Nhs.OpenApi/SwaggerDefinitions/v1.3.0.json
_TD-4107
_Removed Hyper Link  from email address in open api swagger definitions
-----
I have:
> TD-4107-Upadted Email address-Removed Hyperlink  in open API

- WebAPI/LearningHub.Nhs.Database/Stored Procedures/Activity/GetUserLatestActivityCheck.sql
- WebAPI/LearningHub.Nhs.Database/Stored Procedures/Activity/GetUserLearningActivities.sql
- WebAPI/LearningHub.Nhs.Database/Stored Procedures/Activity/GetUserLearningActivitiesCount.sql
_[TD-4261](https://hee-tis.atlassian.net/browse/TD-4261)_
Fixed the duplicate entries for the assessment results showing in my learning activities page. Also made changes to these sps 
as per the suggestions which was pending from EF to SP conversion.
After
-----
I have:
[TD-4261]: https://hee-tis.atlassian.net/browse/TD-4261?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> TD-4261: Duplicate entries for the assessment results(elearning) in the My Learning page

- AdminUI/LearningHub.Nhs.AdminUI/LearningHub.Nhs.AdminUI.csproj
- LearningHub.Nhs.WebUI/LearningHub.Nhs.WebUI.csproj
- LearningHub.Nhs.WebUI/Models/Search/SearchResultViewModel.cs
- LearningHub.Nhs.WebUI/Services/SearchService.cs
- LearningHub.Nhs.WebUI/Views/Search/Index.cshtml
- WebAPI/LearningHub.Nhs.API/Controllers/SearchController.cs
- WebAPI/LearningHub.Nhs.API/LearningHub.Nhs.Api.csproj
- WebAPI/LearningHub.Nhs.Api.Shared/LearningHub.Nhs.Api.Shared.csproj
- WebAPI/LearningHub.Nhs.Api.UnitTests/LearningHub.Nhs.Api.UnitTests.csproj
- WebAPI/LearningHub.Nhs.Repository.Interface/LearningHub.Nhs.Repository.Interface.csproj
- WebAPI/LearningHub.Nhs.Repository/LearningHub.Nhs.Repository.csproj
- WebAPI/LearningHub.Nhs.Services.Interface/LearningHub.Nhs.Services.Interface.csproj
- WebAPI/LearningHub.Nhs.Services.UnitTests/LearningHub.Nhs.Services.UnitTests.csproj
- WebAPI/LearningHub.Nhs.Services/LearningHub.Nhs.Services.csproj
- WebAPI/MigrationTool/LearningHub.Nhs.Migration.ConsoleApp/LearningHub.Nhs.Migration.ConsoleApp.csproj
- WebAPI/MigrationTool/LearningHub.Nhs.Migration.Interface/LearningHub.Nhs.Migration.Interface.csproj
- WebAPI/MigrationTool/LearningHub.Nhs.Migration.Models/LearningHub.Nhs.Migration.Models.csproj
- WebAPI/MigrationTool/LearningHub.Nhs.Migration.Staging.Repository/LearningHub.Nhs.Migration.Staging.Repository.csproj
- WebAPI/MigrationTool/LearningHub.Nhs.Migration.UnitTests/LearningHub.Nhs.Migration.UnitTests.csproj
- WebAPI/MigrationTool/LearningHub.Nhs.Migration/LearningHub.Nhs.Migration.csproj
_[TD-4870](https://hee-tis.atlassian.net/browse/TD-4870)_
Implemented did you mean suggestions in main search results when no results are found.
After
-----
I have:
[TD-4870]: https://hee-tis.atlassian.net/browse/TD-4870?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> TD-4870 : Implemented Did you Mean Feature for Search Search enhancements

- AdminUI/LearningHub.Nhs.AdminUI/wwwroot/css/mkplayer-ui.css
- LearningHub.Nhs.WebUI/wwwroot/css/mkplayer-ui.css
https://hee-tis.atlassian.net/browse/TD-4944
Fixed the issue with UI Overlap on Mobile Devices  
**After Fix**
**Mobile Views**
**System View**
-----
I have:
> TD-4944: UI Overlap on Mobile Devices

- LearningHub.Nhs.WebUI/Controllers/Api/MediaManifestProxyController.cs
- LearningHub.Nhs.WebUI/Controllers/MediaController.cs
- LearningHub.Nhs.WebUI/Views/Home/_CmsVideo.cshtml
_[TD-4945](https://hee-tis.atlassian.net/browse/TD-4945)_
Authorisation issue has been fixed on the landing page.
-----
I have:
[TD-4945]: https://hee-tis.atlassian.net/browse/TD-4945?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> TD-4945: CORS Policy Issue on iPhone Landing Page

- AdminUI/LearningHub.Nhs.AdminUI/Styles/Pages/page_detail.scss
_[TD-4251](https://hee-tis.atlassian.net/browse/TD-4251)_
Fixed the title bold issue on AdminUI when compared with WebUI on safari browser.
-----
I have:
[TD-4251]: https://hee-tis.atlassian.net/browse/TD-4251?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> TD-4251: Fixed title bold issue on admin UI compared to web UI on safari browser

- AdminUI/LearningHub.Nhs.AdminUI/Scripts/vuesrc/content/upload/fileValidation.ts
- WebAPI/LearningHub.Nhs.Database/Scripts/Post-Deploy/Scripts/UpdateFileTypes.sql
https://hee-tis.atlassian.net/browse/TD-4256
'WMV file allowed in the admin UI information page also.
-----
I have:
> WMV file included in the admin UI Information page also

- WebAPI/LearningHub.Nhs.Repository/Resources/BlockCollectionRepository.cs
[TD-4782](https://hee-tis.atlassian.net/browse/TD-4782)
The image processing get stocked because the resource version associated with the whole slide image isn't found, This is cause by the delete block collection SP failing intermittently and thereby not removing obsolete block collections. 
The SP has now been updated to be awaited to fix this task anomaly. 
-----
I have:
[TD-4782]: https://hee-tis.atlassian.net/browse/TD-4782?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> TD-4782 image processing fix

- LearningHub.Nhs.WebUI/Scripts/vuesrc/bookmark/togglebookmark.vue
- LearningHub.Nhs.WebUI/Scripts/vuesrc/catalogue/catalogueaccessrequest.vue
- LearningHub.Nhs.WebUI/Scripts/vuesrc/contribute-resource/ContributeAssessmentSettings.vue
- LearningHub.Nhs.WebUI/Scripts/vuesrc/contribute-resource/ContributeTitle.vue
- LearningHub.Nhs.WebUI/Scripts/vuesrc/contribute-resource/SelectResourceTitle.vue
- LearningHub.Nhs.WebUI/Scripts/vuesrc/contribute-resource/components/questions/MatchGameAnswerOption.vue
- LearningHub.Nhs.WebUI/Scripts/vuesrc/contribute-resource/components/questions/SingleChoiceAnswer.vue
- LearningHub.Nhs.WebUI/Scripts/vuesrc/contribute/Content.vue
- LearningHub.Nhs.WebUI/Scripts/vuesrc/contribute/ContentAudio.vue
- LearningHub.Nhs.WebUI/Scripts/vuesrc/contribute/ContentCommon.vue
- LearningHub.Nhs.WebUI/Scripts/vuesrc/contribute/ContentGenericFile.vue
- LearningHub.Nhs.WebUI/Scripts/vuesrc/contribute/ContentImage.vue
- LearningHub.Nhs.WebUI/Scripts/vuesrc/contribute/ContentWeblink.vue
- LearningHub.Nhs.WebUI/Scripts/vuesrc/resource/ExtraAssessmentAttemptRequestModal.vue
https://hee-tis.atlassian.net/browse/TD-4081
DIG306: Labels for form fields are missing
-----
I have:
> TD-4081:DIG306: Labels for form fields are missing

- LearningHub.Nhs.WebUI/Scripts/vuesrc/contribute-resource/ContributeAuthorsTab.vue
- LearningHub.Nhs.WebUI/Scripts/vuesrc/globalcomponents/CharacterCount.vue
- LearningHub.Nhs.WebUI/Scripts/vuesrc/globalcomponents/CharacterCountWithSaveCancelButtons.vue
- LearningHub.Nhs.WebUI/Views/Shared/Tenant/LearningHub/_Layout.cshtml
_[TD-4072](https://hee-tis.atlassian.net/browse/TD-4072)_
Heading tags are now hidden if it is empty.
-----
I have:
[TD-4072]: https://hee-tis.atlassian.net/browse/TD-4072?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> TD-4072: DIG201 Content has heading markup, but is not a heading issue fixed

- LearningHub.Nhs.WebUI/Scripts/vuesrc/catalogue/managecatalogue.vue
- LearningHub.Nhs.WebUI/Scripts/vuesrc/contribute-resource/Contribute.vue
- LearningHub.Nhs.WebUI/Scripts/vuesrc/contribute-resource/ContributeAssessmentSettings.vue
- LearningHub.Nhs.WebUI/Scripts/vuesrc/contribute-resource/ContributeAuthorsTab.vue
- LearningHub.Nhs.WebUI/Scripts/vuesrc/contribute-resource/ContributeBlock.vue
- LearningHub.Nhs.WebUI/Scripts/vuesrc/contribute-resource/ContributeImageCarouselBlock.vue
- LearningHub.Nhs.WebUI/Scripts/vuesrc/contribute-resource/ContributeImageCarouselBlockItem.vue
- LearningHub.Nhs.WebUI/Scripts/vuesrc/contribute-resource/ContributeWholeSlideImage.vue
- LearningHub.Nhs.WebUI/Scripts/vuesrc/contribute-resource/components/content-tab/MediaBlockCarouselImage.vue
- LearningHub.Nhs.WebUI/Scripts/vuesrc/contribute-resource/components/content-tab/MediaBlockImage.vue
- LearningHub.Nhs.WebUI/Scripts/vuesrc/contribute-resource/components/questions/MultipleChoiceAnswer.vue
- LearningHub.Nhs.WebUI/Scripts/vuesrc/globalcomponents/CharacterCountWithSaveCancelButtons.vue
- LearningHub.Nhs.WebUI/Scripts/vuesrc/globalcomponents/EditSaveFieldWithCharacterCount.vue
- LearningHub.Nhs.WebUI/Scripts/vuesrc/resource/blocks/AnnotationFullPageEdit.vue
https://hee-tis.atlassian.net/browse/TD-4080
DIG302: Placeholder text cannot be used to label forms : accessibility fixes 
-----
I have:
> TD-4080: DIG302: Placeholder text cannot be used to label forms

- LearningHub.Nhs.WebUI/Scripts/vuesrc/contribute-resource/components/KeyWordsEditor.vue
- LearningHub.Nhs.WebUI/Scripts/vuesrc/contribute-resource/components/questions/SingleChoiceAnswer.vue
- LearningHub.Nhs.WebUI/Scripts/vuesrc/contribute/ContentCommon.vue
- LearningHub.Nhs.WebUI/Views/Shared/Components/NavigationItems/MobileTopRightNav.cshtml
- LearningHub.Nhs.WebUI/Views/Shared/_NavPartial.cshtml
https://hee-tis.atlassian.net/browse/TD-4079
accessibility fixes.
DIG301: Form fields are not associated with text labels
-----
I have:
> TD:4079: DIG301: Form fields are not associated with text labels

- LearningHub.Nhs.WebUI/Scripts/vuesrc/contribute-resource/ContributeAssessmentSettings.vue
- LearningHub.Nhs.WebUI/Scripts/vuesrc/contribute-resource/ContributeAuthorsTab.vue
- LearningHub.Nhs.WebUI/Scripts/vuesrc/contribute-resource/ContributeLicenceTab.vue
- LearningHub.Nhs.WebUI/Scripts/vuesrc/contribute-resource/components/CatalogueSelector.vue
- LearningHub.Nhs.WebUI/Scripts/vuesrc/contribute-resource/components/SensitiveContentTickBox.vue
- LearningHub.Nhs.WebUI/Scripts/vuesrc/contribute-resource/components/questions/AllowReveal.vue
- LearningHub.Nhs.WebUI/Scripts/vuesrc/contribute-resource/components/questions/SingleChoiceAnswer.vue
- LearningHub.Nhs.WebUI/Scripts/vuesrc/contribute/CatalogueSelect.vue
- LearningHub.Nhs.WebUI/Scripts/vuesrc/contribute/Content.vue
- LearningHub.Nhs.WebUI/Scripts/vuesrc/contribute/ContentCommon.vue
- LearningHub.Nhs.WebUI/Scripts/vuesrc/contribute/ContentVideo.vue
- LearningHub.Nhs.WebUI/Scripts/vuesrc/learningsessions/ScormViewer.vue
https://hee-tis.atlassian.net/browse/TD-4079
Fixed the accessibility issue - Form elements should have an id attribute.
-----
I have:
> TD-4079: Form elements should have an id attribute

- LearningHub.Nhs.WebUI/Controllers/SearchController.cs
_[TD-4870](https://hee-tis.atlassian.net/browse/TD-4870)_
Fixed the issue related to showing login page in auto suggestion dropdown when timed out.
-----
I have:
[TD-4870]: https://hee-tis.atlassian.net/browse/TD-4870?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> TD-4870: Timeout page not showing properly in search page.

- LearningHub.Nhs.WebUI/Scripts/vuesrc/roadmap/roadmap.vue
- LearningHub.Nhs.WebUI/Views/Home/_CmsPageRow.cshtml
_[TD-4070](https://hee-tis.atlassian.net/browse/TD-4070)_
Removed text from alt attribute for decorative images in Landing page and Service updates and releases page.
-----
I have:
[TD-4070]: https://hee-tis.atlassian.net/browse/TD-4070?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> TD-4070: Removed text from alt attribute for decorative images.

- AdminUI/LearningHub.Nhs.AdminUI/LearningHub.Nhs.AdminUI.csproj
- LearningHub.Nhs.WebUI/Controllers/CatalogueController.cs
- LearningHub.Nhs.WebUI/Controllers/SearchController.cs
- LearningHub.Nhs.WebUI/LearningHub.Nhs.WebUI.csproj
- LearningHub.Nhs.WebUI/Models/Search/SearchResultViewModel.cs
- LearningHub.Nhs.WebUI/Services/SearchService.cs
- LearningHub.Nhs.WebUI/Views/Catalogue/Catalogues.cshtml
- LearningHub.Nhs.WebUI/Views/Search/_CatalogueSearchResult.cshtml
- LearningHub.Nhs.WebUI/Views/Search/_SearchBar.cshtml
- LearningHub.Nhs.WebUI/Views/Shared/Components/NavigationItems/Searchbar.cshtml
- WebAPI/LearningHub.Nhs.API/LearningHub.Nhs.Api.csproj
- WebAPI/LearningHub.Nhs.Api.Shared/LearningHub.Nhs.Api.Shared.csproj
- WebAPI/LearningHub.Nhs.Api.UnitTests/LearningHub.Nhs.Api.UnitTests.csproj
- WebAPI/LearningHub.Nhs.Repository.Interface/LearningHub.Nhs.Repository.Interface.csproj
- WebAPI/LearningHub.Nhs.Repository/LearningHub.Nhs.Repository.csproj
- WebAPI/LearningHub.Nhs.Services.Interface/LearningHub.Nhs.Services.Interface.csproj
- WebAPI/LearningHub.Nhs.Services.UnitTests/LearningHub.Nhs.Services.UnitTests.csproj
- WebAPI/LearningHub.Nhs.Services/LearningHub.Nhs.Services.csproj
- WebAPI/MigrationTool/LearningHub.Nhs.Migration.ConsoleApp/LearningHub.Nhs.Migration.ConsoleApp.csproj
- WebAPI/MigrationTool/LearningHub.Nhs.Migration.Interface/LearningHub.Nhs.Migration.Interface.csproj
- WebAPI/MigrationTool/LearningHub.Nhs.Migration.Models/LearningHub.Nhs.Migration.Models.csproj
- WebAPI/MigrationTool/LearningHub.Nhs.Migration.Staging.Repository/LearningHub.Nhs.Migration.Staging.Repository.csproj
- WebAPI/MigrationTool/LearningHub.Nhs.Migration.UnitTests/LearningHub.Nhs.Migration.UnitTests.csproj
- WebAPI/MigrationTool/LearningHub.Nhs.Migration/LearningHub.Nhs.Migration.csproj
_[TD-4870](https://hee-tis.atlassian.net/browse/TD-4870)_
Fixed Timeout issue and mismatch in counts in view all catalogue page from main search results page.
-----
I have:
[TD-4870]: https://hee-tis.atlassian.net/browse/TD-4870?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> TD-4870: Fixed Timeout issue and mismatch in counts in view all catalogue page

- LearningHub.Nhs.WebUI/Models/Search/SearchResultViewModel.cs
- LearningHub.Nhs.WebUI/Services/SearchService.cs
- LearningHub.Nhs.WebUI/Views/Search/Index.cshtml
_[TD-4870](https://hee-tis.atlassian.net/browse/TD-4870)_
Changed the suggestion message and now showing the suggested terms as well.
After
-----
I have:
[TD-4870]: https://hee-tis.atlassian.net/browse/TD-4870?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> TD-4870: Change in did you mean suggestion message

- AdminUI/LearningHub.Nhs.AdminUI/LearningHub.Nhs.AdminUI.csproj
- LearningHub.Nhs.WebUI/Controllers/SearchController.cs
- LearningHub.Nhs.WebUI/Interfaces/ISearchService.cs
- LearningHub.Nhs.WebUI/LearningHub.Nhs.WebUI.csproj
- LearningHub.Nhs.WebUI/Services/SearchService.cs
- LearningHub.Nhs.WebUI/Views/Search/_AutoComplete.cshtml
- WebAPI/LearningHub.Nhs.API/Controllers/SearchController.cs
- WebAPI/LearningHub.Nhs.API/LearningHub.Nhs.Api.csproj
- WebAPI/LearningHub.Nhs.API/appsettings.json
- WebAPI/LearningHub.Nhs.Api.Shared/Configuration/FindwiseSettings.cs
- WebAPI/LearningHub.Nhs.Api.Shared/LearningHub.Nhs.Api.Shared.csproj
- WebAPI/LearningHub.Nhs.Api.UnitTests/LearningHub.Nhs.Api.UnitTests.csproj
- WebAPI/LearningHub.Nhs.Repository.Interface/LearningHub.Nhs.Repository.Interface.csproj
- WebAPI/LearningHub.Nhs.Repository/LearningHub.Nhs.Repository.csproj
- WebAPI/LearningHub.Nhs.Services.Interface/ISearchService.cs
- WebAPI/LearningHub.Nhs.Services.Interface/LearningHub.Nhs.Services.Interface.csproj
- WebAPI/LearningHub.Nhs.Services.UnitTests/LearningHub.Nhs.Services.UnitTests.csproj
- WebAPI/LearningHub.Nhs.Services/LearningHub.Nhs.Services.csproj
- WebAPI/LearningHub.Nhs.Services/SearchService.cs
- WebAPI/MigrationTool/LearningHub.Nhs.Migration.ConsoleApp/LearningHub.Nhs.Migration.ConsoleApp.csproj
- WebAPI/MigrationTool/LearningHub.Nhs.Migration.Interface/LearningHub.Nhs.Migration.Interface.csproj
- WebAPI/MigrationTool/LearningHub.Nhs.Migration.Models/LearningHub.Nhs.Migration.Models.csproj
- WebAPI/MigrationTool/LearningHub.Nhs.Migration.Staging.Repository/LearningHub.Nhs.Migration.Staging.Repository.csproj
- WebAPI/MigrationTool/LearningHub.Nhs.Migration.UnitTests/LearningHub.Nhs.Migration.UnitTests.csproj
- WebAPI/MigrationTool/LearningHub.Nhs.Migration/LearningHub.Nhs.Migration.csproj
_[TD-4824](https://hee-tis.atlassian.net/browse/TD-4824)_
Implemented click logs for Auto suggestions and also included the redirection to resources/catalogues from suggestions list.
-----
I have:
[TD-4824]: https://hee-tis.atlassian.net/browse/TD-4824?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> TD-4824: Implemented click logs for Auto suggestions.

- LearningHub.Nhs.WebUI/Views/Shared/Components/DateInput/Default.cshtml
_[TD-5080](https://hee-tis.atlassian.net/browse/TD-5080)_
Issue fixed on zero not allowing to enter on date field.
-----
I have:
[TD-5080]: https://hee-tis.atlassian.net/browse/TD-5080?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> TD-5080: Issue on 'Enter your start date' screen not allowing to add '0' to date field

- LearningHub.Nhs.WebUI/Styles/nhsuk/pages/search.scss
TD-4192
DIG818: Focus is not rendered correctly
-----
I have:
> TD 4192 -DIG818: Focus is not rendered correctly

- LearningHub.Nhs.WebUI/Views/Account/CreateAccountCountrySearch.cshtml
- LearningHub.Nhs.WebUI/Views/Account/CreateAccountSearchRole.cshtml
- LearningHub.Nhs.WebUI/Views/Account/CreateAccountWorkPlaceSearch.cshtml
_[TD-4180](https://hee-tis.atlassian.net/browse/TD-4180)_
Error message changed according to NHS design pattern in pages selecting country, role and place of work.
-----
I have:
[TD-4180]: https://hee-tis.atlassian.net/browse/TD-4180?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> TD-4180: Error message changed according to NHS design pattern

- LearningHub.Nhs.WebUI/Views/Shared/Components/DateInput/Default.cshtml
_[TD-4183](https://hee-tis.atlassian.net/browse/TD-4183)_
Corrected the error messages for the start date according to the NHS design standards.
-----
I have:
[TD-4183]: https://hee-tis.atlassian.net/browse/TD-4183?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> TD-4183: Corrected the error messages for the start date.

- LearningHub.Nhs.WebUI/Scripts/vuesrc/mycontributions/gridcardcomponent.vue
_[TD-4196](https://hee-tis.atlassian.net/browse/TD-4196)_
Removed tab index 0 from non interactive elements.
-----
I have:
[TD-4196]: https://hee-tis.atlassian.net/browse/TD-4196?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> TD-4196: Non-interactive content receives focus without good reason

- LearningHub.Nhs.WebUI/Controllers/AccountController.cs
- LearningHub.Nhs.WebUI/LearningHub.Nhs.WebUI.csproj
- LearningHub.Nhs.WebUI/Views/Account/CreateAccountCountrySelection.cshtml
- LearningHub.Nhs.WebUI/Views/Account/CreateAccountCurrentRole.cshtml
- LearningHub.Nhs.WebUI/Views/Account/CreateAccountEmailVerification.cshtml
- LearningHub.Nhs.WebUI/Views/Account/CreateAccountGradeSelection.cshtml
- LearningHub.Nhs.WebUI/Views/Account/CreateAccountPersonalDetails.cshtml
- LearningHub.Nhs.WebUI/Views/Account/CreateAccountPrimarySpecialtySelection.cshtml
- LearningHub.Nhs.WebUI/Views/Account/CreateAccountRegionSelection.cshtml
- LearningHub.Nhs.WebUI/Views/Account/CreateAccountWorkPlace.cshtml
- LearningHub.Nhs.WebUI/Views/Account/CreateAccountWorkStartDate.cshtml
- LearningHub.Nhs.WebUI/Views/Shared/Tenant/LearningHub/_Layout.cshtml
- LearningHub.Nhs.WebUI/Views/Shared/_ValidationScriptsPartial.cshtml
_[TD-4180](https://hee-tis.atlassian.net/browse/TD-4180)_
Conditionally removed js validations from LH create account pages.
-----
I have:
[TD-4180]: https://hee-tis.atlassian.net/browse/TD-4180?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> TD-4180: Moved client side validations to server side.

- AdminUI/LearningHub.Nhs.AdminUI/LearningHub.Nhs.AdminUI.csproj
- LearningHub.Nhs.WebUI/LearningHub.Nhs.WebUI.csproj
- OpenAPI/LearningHub.Nhs.OpenApi.Models/LearningHub.Nhs.OpenApi.Models.csproj
- OpenAPI/LearningHub.Nhs.OpenApi.Services.Interface/LearningHub.Nhs.OpenApi.Services.Interface.csproj
- OpenAPI/LearningHub.Nhs.OpenApi.Services/LearningHub.Nhs.OpenApi.Services.csproj
- WebAPI/LearningHub.Nhs.API/LearningHub.Nhs.Api.csproj
- WebAPI/LearningHub.Nhs.Api.Shared/LearningHub.Nhs.Api.Shared.csproj
- WebAPI/LearningHub.Nhs.Api.UnitTests/LearningHub.Nhs.Api.UnitTests.csproj
- WebAPI/LearningHub.Nhs.Database/LearningHub.Nhs.Database.sqlproj
- WebAPI/LearningHub.Nhs.Database/Stored Procedures/Activity/GetAssessmentActivityCompletionPercentage.sql
- WebAPI/LearningHub.Nhs.Database/Stored Procedures/Activity/GetUserLatestActivityCheck.sql
- WebAPI/LearningHub.Nhs.Database/Stored Procedures/Activity/GetUserLearningActivities.sql
- WebAPI/LearningHub.Nhs.Database/Stored Procedures/Activity/GetUserLearningActivitiesCount.sql
- WebAPI/LearningHub.Nhs.Repository.Interface/Activity/IResourceActivityRepository.cs
- WebAPI/LearningHub.Nhs.Repository.Interface/LearningHub.Nhs.Repository.Interface.csproj
- WebAPI/LearningHub.Nhs.Repository/Activity/ResourceActivityRepository.cs
- WebAPI/LearningHub.Nhs.Repository/LearningHub.Nhs.Repository.csproj
- WebAPI/LearningHub.Nhs.Repository/LearningHubDbContext.cs
- WebAPI/LearningHub.Nhs.Services.Interface/LearningHub.Nhs.Services.Interface.csproj
- WebAPI/LearningHub.Nhs.Services.UnitTests/LearningHub.Nhs.Services.UnitTests.csproj
- WebAPI/LearningHub.Nhs.Services/LearningHub.Nhs.Services.csproj
- WebAPI/LearningHub.Nhs.Services/MyLearningService.cs
- WebAPI/MigrationTool/LearningHub.Nhs.Migration.ConsoleApp/LearningHub.Nhs.Migration.ConsoleApp.csproj
- WebAPI/MigrationTool/LearningHub.Nhs.Migration.Interface/LearningHub.Nhs.Migration.Interface.csproj
- WebAPI/MigrationTool/LearningHub.Nhs.Migration.Models/LearningHub.Nhs.Migration.Models.csproj
- WebAPI/MigrationTool/LearningHub.Nhs.Migration.Staging.Repository/LearningHub.Nhs.Migration.Staging.Repository.csproj
- WebAPI/MigrationTool/LearningHub.Nhs.Migration.UnitTests/LearningHub.Nhs.Migration.UnitTests.csproj
- WebAPI/MigrationTool/LearningHub.Nhs.Migration/LearningHub.Nhs.Migration.csproj
https://hee-tis.atlassian.net/browse/TD-5078
Improved the performance of my learning page by refractering the logic.
https://github.com/user-attachments/assets/2de4e29b-d61a-4d46-a584-a017419f46a7
-----
I have:
> TD-5078: My Learning page - activity not loading for user

- LearningHub.Nhs.WebUI/Views/Shared/Components/DateInput/Default.cshtml
- LearningHub.Nhs.WebUI/Views/Shared/Components/ErrorSummary/Default.cshtml
- LearningHub.Nhs.WebUI/Views/Shared/Components/RadioList/Default.cshtml
_[TD-4180](https://hee-tis.atlassian.net/browse/TD-4180)_
Updating auto generated View Component files.
-----
I have:
[TD-4180]: https://hee-tis.atlassian.net/browse/TD-4180?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> TD-4180: Updating View Component files

- LearningHub.Nhs.WebUI/Interfaces/IFileService.cs
- LearningHub.Nhs.WebUI/Models/FileDownloadResponse.cs
- LearningHub.Nhs.WebUI/Services/FileService.cs
[TD-5176](https://hee-tis.atlassian.net/browse/TD-5176)
I've added a logic to download files less than or equal to 500mb using our default download method directly to the browser, otherwise download the files in chunks of 100mb , with up to 8 simultaneous download at the webserver and output the entire file to the browser at once
-----
I have:
[TD-5176]: https://hee-tis.atlassian.net/browse/TD-5176?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> TD-5176 Large file download fix.

- LearningHub.Nhs.WebUI/Controllers/AccountController.cs
_[TD-5130](https://hee-tis.atlassian.net/browse/TD-5130)_
Clearing country selection on new search
-----
I have:
[TD-5130]: https://hee-tis.atlassian.net/browse/TD-5130?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> TD-5130: Clearing country selection on new search

- LearningHub.Nhs.WebUI/Services/FileService.cs
[TD-5176](https://hee-tis.atlassian.net/browse/TD-5176)
Reverted initial code changes as the fix for this issue is an environment-related change.
-----
I have:
[TD-5176]: https://hee-tis.atlassian.net/browse/TD-5176?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> TD-5176 file download refactor

- LearningHub.Nhs.WebUI/Views/Account/CreateAccountSearchRole.cshtml
_[TD-5130](https://hee-tis.atlassian.net/browse/TD-5130)_
Fixed unknown error when going back to country page from search role page.
-----
I have:
[TD-5130]: https://hee-tis.atlassian.net/browse/TD-5130?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> TD-5130: Fixed unknown error

- LearningHub.Nhs.WebUI/Services/FileService.cs
TD-5176
Updated the code to stream files larger than 900mb directly to the browser. All download work perfectly fine locally but fails intermittently in other environment.
-----
I have:
> download file code refactor to stream large file rather than downloading files internally

- LearningHub.Nhs.WebUI/Controllers/AccountController.cs
- LearningHub.Nhs.WebUI/Helpers/AccountCreationFormHelper.cs
- LearningHub.Nhs.WebUI/LearningHub.Nhs.WebUI.csproj
- LearningHub.Nhs.WebUI/Views/Account/CreateAccountPrimarySpecialty.cshtml
- LearningHub.Nhs.WebUI/Views/Account/CreateAccountPrimarySpecialtySelection.cshtml
- LearningHub.Nhs.WebUI/Views/Shared/Components/RadioList/Default.cshtml
[TD-4180](https://hee-tis.atlassian.net/browse/TD-4180)
Grouped form controls within the view component has now been updated to focus on the first item in a radio list when an error occurred. A viewdata was introduced to capture form fields that are grouped. This allows  the view component to assign the correct incremental ID which aligns with how IDs are generated in a radiogroup.
-----
I have:
[TD-4180]: https://hee-tis.atlassian.net/browse/TD-4180?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> programmatically associating error summary with  form field

- LearningHub.Nhs.WebUI/Controllers/AccountController.cs
TD-4180
Added a missing line of code which helps with the identification of grouped form control.
-----
I have:
> TD-4180 update

- LearningHub.Nhs.WebUI/Controllers/AccountController.cs
TD-4180
Fixed a backlink missing a parameter, and subsequently loosing a selected option in previous screen.
-----
I have:
> Added a missing parameter - gardeId

- LearningHub.Nhs.WebUI/Scripts/vuesrc/resource/ResourceContent.vue
_TD-5238
elearning resource page doesn't refresh properly upon completing elearning
-----
I have:
> TD-5238-elearning resource page doesn't refresh properly upon completing elearning

- WebAPI/LearningHub.Nhs.Database/Stored Procedures/Resources/GetMyInProgressDashboardResources.sql
https://hee-tis.atlassian.net/browse/TD-5255
The My learning page does show the activity but it's not showing up under accessed learning
-----
I have:
Either:
Or:
> Develop/fixes/td 5255 my learning page does show the activity but it's not showing up under accessed learning

- LearningHub.Nhs.WebUI/Views/Home/_CmsVideo.cshtml
- LearningHub.Nhs.WebUI/wwwroot/js/mkplayer-ui-custom.js
https://hee-tis.atlassian.net/browse/TD-5300
Landing Page - Video player buttons focus right to left  - fixed the issue with the focus.
-----
I have:
Either:
Or:
> TD-5300: Landing Page - Video player buttons focus right to left

- WebAPI/LearningHub.Nhs.Database/Scripts/ELFH Database Scripts/Update LH email content.sql
_[TD-5001](https://hee-tis.atlassian.net/browse/TD-5001)_
Word "Support" is removed from the automated mails during account creation.
-----
I have:
[TD-5001]: https://hee-tis.atlassian.net/browse/TD-5001?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> TD-5001: Word "Support" placement

- LearningHub.Nhs.WebUI/Views/Account/CreateAccountEmailVerification.cshtml
- LearningHub.Nhs.WebUI/Views/Account/CreateAccountRegistrationInformation.cshtml
- WebAPI/LearningHub.Nhs.Database/Scripts/ELFH Database Scripts/Update LH email content.sql
[TD-4931](https://hee-tis.atlassian.net/browse/TD-4931)
Merge changes from User-Registration-Journey to Dahila
-----
I have:
Either:
Or:
[TD-4931]: https://hee-tis.atlassian.net/browse/TD-4931?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Merge changes from User-Registration-Journey to Dahila

- LearningHub.Nhs.WebUI/Controllers/Api/ResourceController.cs
- LearningHub.Nhs.WebUI/Models/FileDownloadResponse.cs
- LearningHub.Nhs.WebUI/Services/FileService.cs
[TD-5348](https://hee-tis.atlassian.net/browse/TD-5348)
Modified file service to generate azure storage link for files larger than 999mb
-----
I have:
Either:
Or:
[TD-5348]: https://hee-tis.atlassian.net/browse/TD-5348?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> TD-5348 LH resource download files error

- LearningHub.Nhs.WebUI/Views/Home/Contactus.cshtml
TD-5302
fix for Contact Us Page - Two headings have the same heading level
-----
I have:
Either:
Or:
> TD-5302-Fix for Contact Us Page - Two headings have the same heading level

- OpenAPI/LearningHub.Nhs.OpenApi.Models/Configuration/FindwiseCollectionIdSettings.cs
- OpenAPI/LearningHub.Nhs.OpenApi.Services.Interface/Services/ISearchService.cs
- OpenAPI/LearningHub.Nhs.OpenApi.Services/Services/SearchService.cs
- OpenAPI/LearningHub.Nhs.OpenApi/Controllers/SearchController.cs
- OpenAPI/LearningHub.Nhs.OpenApi/appsettings.json
[TD-5384](https://hee-tis.atlassian.net/browse/TD-5384)
Added the autosuggestion search endpoint to the openAPI project
-----
I have:
Either:
Or:
[TD-5384]: https://hee-tis.atlassian.net/browse/TD-5384?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Added Autosuggestion

- LearningHub.Nhs.WebUI/Views/Account/CreateAccountEmailVerification.cshtml
[TD-4967](https://hee-tis.atlassian.net/browse/TD-4967)
Rewording on email verification page.
After
-----
I have:
Either:
Or:
[TD-4967]: https://hee-tis.atlassian.net/browse/TD-4967?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> TD-4967: Rewording on email verification page.

- LearningHub.Nhs.WebUI/Controllers/HomeController.cs
- LearningHub.Nhs.WebUI/LearningHub.Nhs.WebUI.csproj
- LearningHub.Nhs.WebUI/Middleware/LHIPRateLimitMiddleware.cs
- LearningHub.Nhs.WebUI/Program.cs
- LearningHub.Nhs.WebUI/ServiceCollectionExtension.cs
- LearningHub.Nhs.WebUI/Views/Shared/TooManyRequests.cshtml
- LearningHub.Nhs.WebUI/appsettings.json
https://hee-tis.atlassian.net/browse/TD-3730
Implemented rate limiting to prevent email flooding attacks using AspNetCoreRateLimit Middleware
-----
I have:
Either:
Or:
> TD-3730: No Rate Limiting Enabled

- LearningHub.Nhs.WebUI/Helpers/InMemoryTicketStore.cs
- LearningHub.Nhs.WebUI/Startup/AuthenticationConfiguration.cs
https://hee-tis.atlassian.net/browse/TD-3734
The application should detect the second authentication event and invalidate the initial session.
-----
I have:
Either:
Or:
> TD-3743: Concurrent Sessions Allowed

- LearningHub.Nhs.WebUI/Controllers/AccountController.cs
- LearningHub.Nhs.WebUI/Models/Account/AccountCreationDateViewModel.cs
[TD-5134](https://hee-tis.atlassian.net/browse/TD-5134)
Fixed the issue to retain the input text even if error occurs
-----
I have:
Either:
Or:
[TD-5134]: https://hee-tis.atlassian.net/browse/TD-5134?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> TD-5134: Fixed issue not showing the inputted text on the date fields when there is an error on the screen

- LearningHub.Nhs.WebUI/Scripts/vuesrc/notification/notifications.vue
[TD-5170](https://hee-tis.atlassian.net/browse/TD-5170)
Fixed console errors on notifications page
-----
I have:
Either:
Or:
[TD-5170]: https://hee-tis.atlassian.net/browse/TD-5170?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> TD-5170: Issue showing console errors on few of the 'create new account' flow screens & 'Notifications'

- LearningHub.Nhs.WebUI/Views/Shared/_LoginBanner.cshtml
TD-5648
Catalogue forgotten password links goes to error page
-----
I have:
Either:
Or:
> TD-5648-Catalogue forgotten password links goes to error page

- LearningHub.Nhs.WebUI/Styles/nhsuk/pages/search.scss
[TD-5509](https://hee-tis.atlassian.net/browse/TD-5509)
Fixed the catalogue pagination width on search results page.
-----
I have:
Either:
Or:
[TD-5509]: https://hee-tis.atlassian.net/browse/TD-5509?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> TD-5509: Fixed the catalogue pagination width

- OpenAPI/LearningHub.Nhs.OpenApi/SwaggerDefinitions/v1.3.0.json
TD-5118
reverted the merge of previous endpoint description with the new endpoint descriptions. The description of the entire endpoint would be fixed in a follow up ticket
-----
I have:
Either:
Or:
> Revert documentation of swagger descriptions

- LearningHub.Nhs.MessagingService/Interfaces/IGovNotifyService.cs
- LearningHub.Nhs.MessagingService/LearningHub.Nhs.MessagingService.csproj
- LearningHub.Nhs.MessagingService/Model/MessagingServiceModel.cs
- LearningHub.Nhs.MessagingService/Model/SendEmailRequest.cs
- LearningHub.Nhs.MessagingService/Model/SendSmsRequest.cs
- LearningHub.Nhs.MessagingService/Services/GovNotifyService.cs
- LearningHub.Nhs.MessagingService/Startup.cs
- LearningHub.Nhs.WebUI.sln
- OpenAPI/LearningHub.Nhs.OpenApi/Controllers/GovNotifyMessagingController.cs
- OpenAPI/LearningHub.Nhs.OpenApi/LearningHub.NHS.OpenAPI.csproj
- OpenAPI/LearningHub.Nhs.OpenApi/Startup.cs
- OpenAPI/LearningHub.Nhs.OpenApi/SwaggerDefinitions/v1.3.0.json
- OpenAPI/LearningHub.Nhs.OpenApi/appsettings.json
[TD-5474](https://hee-tis.atlassian.net/browse/TD-5474)
Create a new messaging service project using Gov.Notify
-----
I have:
Either:
Or:
[TD-5474]: https://hee-tis.atlassian.net/browse/TD-5474?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> TD-5474: Create a new messaging service project

- LearningHub.Nhs.WebUI/Scripts/vuesrc/contribute/Content.vue
- LearningHub.Nhs.WebUI/Scripts/vuesrc/contribute/fileUpload.vue
https://hee-tis.atlassian.net/browse/TD-3727
Fixed the SIT comments
1. In all cases of uploading a file that is not in the resource.filetype table, you are presented with the same error (problem uploading zip), even if it’s not a zip file. Should there not be some sort of catch-all in the filetype table that captures everything that is not accepted and gives the same error for consistency?
e.g. We do not support this file type on the Learning Hub.
Please see our support article which describes the file types that can be uploaded to the Learning Hub. - **Corrected the error messages**
bonus fix - after entering your password when uploading a file, pressing enter should submit it. Currently you have to move your mouse and hit “continue” - **Fixed**
_Paste screenshots for all views created …
> TD-3727- Unrestricted file upload- SIT comments

- LearningHub.Nhs.WebUI/Controllers/HomeController.cs
- LearningHub.Nhs.WebUI/Interfaces/IUserService.cs
- LearningHub.Nhs.WebUI/LearningHub.Nhs.WebUI.csproj
- LearningHub.Nhs.WebUI/Services/UserService.cs
- LearningHub.Nhs.WebUI/Views/Account/AlreadyAnActiveSession.cshtml
https://hee-tis.atlassian.net/browse/TD-3734
Concurrent Sessions Allowed - SIT fixes
-----
I have:
Either:
Or:
> TD-3734-Concurrent session-SIT fixes

- AdminUI/LearningHub.Nhs.AdminUI/web.config
- LearningHub.Nhs.WebUI/Controllers/AccountController.cs
- LearningHub.Nhs.WebUI/Services/UserService.cs
- LearningHub.Nhs.WebUI/Views/Account/AlreadyAnActiveSession.cshtml
- LearningHub.Nhs.WebUI/web.config
- WebAPI/LearningHub.Nhs.API/web.config
[TD-5538](https://hee-tis.atlassian.net/browse/TD-5538)
Included web.config in the solution to add security headers
-----
I have:
Either:
Or:
[TD-5538]: https://hee-tis.atlassian.net/browse/TD-5538?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Develop/fixes/lh td 5538 update web.config file

- AdminUI/LearningHub.Nhs.AdminUI/Views/Resource/Details.cshtml
TD-5595
LH Admin - HTML resource details cannot be seen in Resource tab
-----
I have:
- [ X] Run the IDE auto formatter on all files I’ve worked on and made sure there are no IDE errors relating to them
Either:
Or:
> TD-5595-LH Admin - HTML resource details cannot be seen in Resource tab

- OpenAPI/LearningHub.Nhs.OpenApi.Services.Interface/Services/IUserGroupService.cs
- OpenAPI/LearningHub.Nhs.OpenApi.Services/Services/NavigationPermissionService.cs
- OpenAPI/LearningHub.Nhs.OpenApi.Services/Services/UserGroupService.cs
- OpenAPI/LearningHub.Nhs.OpenApi.Services/Startup.cs
[TD-5560](https://hee-tis.atlassian.net/browse/TD-5560)
-----
I have:
Either:
Or:
[TD-5560]: https://hee-tis.atlassian.net/browse/TD-5560?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> lh menu permisiion update for contribution

- LearningHub.Nhs.WebUI/Scripts/vuesrc/contribute-resource/components/CatalogueSelectorAccordion.vue
- LearningHub.Nhs.WebUI/Scripts/vuesrc/contribute/CatalogueSelect.vue
- LearningHub.Nhs.WebUI/Services/UserGroupService.cs
[TD-5665](https://hee-tis.atlassian.net/browse/TD-5665)
Community Contribution suspended
-----
I have:
Either:
Or:
[TD-5665]: https://hee-tis.atlassian.net/browse/TD-5665?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> TD-5665: Community Contribution Suspend

- OpenAPI/LearningHub.Nhs.OpenApi.Services/Services/MyLearningService.cs
[TD-5500](https://hee-tis.atlassian.net/browse/TD-5500)
Fix to correct the Invalid date time  in my learning page
-----
I have:
Either:
Or:
[TD-5500]: https://hee-tis.atlassian.net/browse/TD-5500?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> TD-5500: Invalid date time in my learning page

- LearningHub.Nhs.WebUI/Views/Home/_ResourceTray.cshtml
TD-5700
Reorder resource tabs on LH home page
1.Highly rated
2.Recently Added
3.Most accessed
-----
I have:
Either:
Or:
> TD-5700- Reorder resource tabs on LH home page 

- LearningHub.Nhs.WebUI/Styles/nhsuk/layout.scss
- LearningHub.Nhs.WebUI/Styles/nhsuk/nhsuk-overrides.scss
[TD-5836](https://hee-tis.atlassian.net/browse/TD-5836)
css definitions relating to banner images and "checkbox css trick" checkboxes was moved from media query to base styles.
-----
I have:
Either:
Or:
[TD-5836]: https://hee-tis.atlassian.net/browse/TD-5836?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fixed banner image and checkbox scss bug

- LearningHub.Nhs.WebUI/Models/SideMenu/SideNavViewModel.cs
- LearningHub.Nhs.WebUI/Models/SideMenu/SideNavigationConfiguration.cs
- LearningHub.Nhs.WebUI/Models/SideMenu/SideNavigationGroup.cs
- LearningHub.Nhs.WebUI/Models/SideMenu/SideNavigationItem.cs
- LearningHub.Nhs.WebUI/Styles/nhsuk/layout.scss
- LearningHub.Nhs.WebUI/ViewComponents/SideNavViewComponent.cs
- LearningHub.Nhs.WebUI/Views/Shared/Components/SideNav/Default.cshtml
[TD-5762](https://hee-tis.atlassian.net/browse/TD-5762)
The idea is based off the DLS implementation with some slight changes
-To get this working, we need to add menu items in the SideMenuConfiguartion file within the model folder.
-Initialise it in any area of the LH razor view using the code below:
@await Component.InvokeAsync("SideNav", new { groupTitle = "Account" })
**MOBILE**
**DESKTOP**
-----
I have:
Either:
Or:
[TD-5762]: https://hee-tis.atlassian.net/browse/TD-5762?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Left hand navigation implementation

- LearningHub.Nhs.WebUI/Controllers/ContributeController.cs
TD-5727
_-Fix for Full user who is not a catalogue editor/admin can access My contribution page by navigating to the link directly
-----
I have:
Either:
Or:
>  TD-5727-Fix for Full user who is not a catalogue editor/admin can access My contribution page by navigating to the link directly 

- OpenAPI/LearningHub.Nhs.OpenApi/Controllers/BookmarkController.cs
- OpenAPI/LearningHub.Nhs.OpenApi/Controllers/CatalogueController.cs
- OpenAPI/LearningHub.Nhs.OpenApi/Controllers/ResourceController.cs
- OpenAPI/LearningHub.Nhs.OpenApi/Controllers/SearchController.cs
- OpenAPI/LearningHub.Nhs.OpenApi/Startup.cs
[TD-5921](https://hee-tis.atlassian.net/browse/TD-5921)
API request when user is yet to login returns a 500 error.
This was resolved by applying a default authentication scheme and also , commenting out the clobal authorize filter which then overrides the custom authorize policies defined
-----
I have:
Either:
Or:
[TD-5921]: https://hee-tis.atlassian.net/browse/TD-5921?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> TD-5490 auth issues for LH api  request when user is yet to login

- LearningHub.Nhs.WebUI/Controllers/LoginWizardController.cs
- LearningHub.Nhs.WebUI/Controllers/MyAccountController.cs
- LearningHub.Nhs.WebUI/Styles/nhsuk/layout.scss
- LearningHub.Nhs.WebUI/Views/LoginWizard/SecurityQuestionsDetails.cshtml
- LearningHub.Nhs.WebUI/Views/MyAccount/Index.cshtml
- LearningHub.Nhs.WebUI/Views/MyAccount/MyEmployment.cshtml
- LearningHub.Nhs.WebUI/Views/MyAccount/_MyAccountSecurityQuestions.cshtml
[TD-6101](https://hee-tis.atlassian.net/browse/TD-6101)
Updated the login wizard controller, changed the redirection from old my account screens to new my account screens.
-----
I have:
Either:
Or:
[TD-6101]: https://hee-tis.atlassian.net/browse/TD-6101?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> TD-6101: Login Wizard changes

- WebAPI/LearningHub.Nhs.Database/Stored Procedures/Resources/GetUsercertificateDetails.sql
TD-5765
update  to always use activity end date but where such is null as we have in some resource type(e.g article), use activity start date.
-----
I have:
Either:
Or:
> TD-5765 null check for activity start and end date

- LearningHub.Nhs.WebUI/Views/MyLearning/Index.cshtml
- OpenAPI/LearningHub.Nhs.OpenApi.Repositories/Repositories/Activity/ResourceActivityRepository.cs
- OpenAPI/LearningHub.Nhs.OpenApi.Services/Services/MyLearningService.cs
To check the issue with the recent learning page.
-----
I have:
Either:
Or:
> fixes to check recent Learning  activity iossue

- WebAPI/LearningHub.Nhs.Database/LearningHub.Nhs.Database.sqlproj
- WebAPI/LearningHub.Nhs.Database/Scripts/Post-Deploy/Scripts/TD-6109_Enable_CDC.sql
TD-6109
Enable the following tables for CDC / CT in the Learning Hub
-----
I have:
Either:
Or:
> TD-6109-Enable the following tables for CDC / CT in the Learning Hub

- LearningHub.Nhs.WebUI/Models/SideMenu/SideNavigationConfiguration.cs
- LearningHub.Nhs.WebUI/Scripts/vuesrc/notification/notifications.vue
- LearningHub.Nhs.WebUI/Views/Notification/Index.cshtml
[TD-6147](https://hee-tis.atlassian.net/browse/TD-6147)
Fixed issue with the wording of the headings on the 'My account - Notifications' screen
-----
I have:
Either:
Or:
[TD-6147]: https://hee-tis.atlassian.net/browse/TD-6147?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> TD-6147: Fixed issue with the wording of the headings on the 'My account - Notifications' screen

- LearningHub.Nhs.WebUI/Controllers/LoginWizardController.cs
- LearningHub.Nhs.WebUI/Controllers/MyAccountController.cs
- LearningHub.Nhs.WebUI/Styles/nhsuk/layout.scss
- LearningHub.Nhs.WebUI/Styles/nhsuk/nhsuk-overrides.scss
- LearningHub.Nhs.WebUI/Views/MyAccount/ChangePassword.cshtml
- LearningHub.Nhs.WebUI/Views/MyAccount/ConfirmPassword.cshtml
- LearningHub.Nhs.WebUI/Views/MyAccount/MyAccountSecurityQuestionsDetails.cshtml
- LearningHub.Nhs.WebUI/Views/Shared/Components/NavigationItems/Topnav.cshtml
[TD-6138](https://hee-tis.atlassian.net/browse/TD-6138)
TD-6138: Fixed issue son security tab on my account and added user icon.
-----
I have:
Either:
Or:
[TD-6138]: https://hee-tis.atlassian.net/browse/TD-6138?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> TD-6138: Fixed issues on security tab on my account and added user icon.

- OpenAPI/LearningHub.Nhs.OpenApi.Services/Services/MyLearningService.cs
- WebAPI/LearningHub.Nhs.Database/Stored Procedures/Resources/GetUsercertificateDetails.sql
[TD-6213 ](https://hee-tis.atlassian.net/browse/TD-6213)
make certificate available for informal certificate once status is completed and ignore if user pass or fail or pass mark of assessment
-----
I have:
Either:
Or:
> TD-6213 make certificate available for informal certificate without passmark condition

- LearningHub.Nhs.WebUI/Views/Home/_MyCoursesAndElearning.cshtml
- LearningHub.Nhs.WebUI/Views/MyLearning/LearningCertificate.cshtml
TD-6318
My courses and learning dashboard - wording of "Elearning" wrong case
-----
I have:
Either:
Or:
> TD-6318-My courses and learning dashboard - wording of "Elearning" wrong case
